---
sidebar: sidebar 
permalink: faq-cloud-compliance.html 
keywords: faq, frequently asked questions, questions, cloud compliance, data sense 
summary: 如果您只是想快速了解问题解答，此常见问题解答会很有帮助。 
---
= 有关BlueXP分类的常见问题
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您只是想快速了解问题解答，此常见问题解答会很有帮助。



== BlueXP分类服务

以下问题概括说明了BlueXP分类。



=== BlueXP分类的工作原理是什么？

BlueXP  分类可在您的BlueXP  系统和存储系统旁边部署另一层AI。然后、它会扫描卷、分段、数据库和其他存储帐户上的数据、并为找到的数据洞察力编制索引。BlueXP分类利用人工智能和自然语言处理、而不是通常围绕正则表达式和模式匹配构建的替代解决方案。

BlueXP分类使用AI提供对数据的上下文了解、以实现准确的检测和分类。它由AI驱动、因为它专为现代数据类型和规模而设计。它还了解数据环境、以便提供强大、准确的发现和分类。

link:concept-cloud-compliance.html["详细了解BlueXP分类的工作原理"](英文)



=== BlueXP分类是否具有REST API？是否可与第三方工具配合使用？

是的、BlueXP  分类为BlueXP  核心平台中的BlueXP  分类版本中支持的功能提供了一个REST API。请参阅。 link:api-classification.html["API 文档"]



=== BlueXP  分类是否可通过云市场获得？

BlueXP  分类是BlueXP  核心功能的一部分，因此您不需要使用此服务的商城。



== BlueXP分类扫描和分析

以下问题与BlueXP  分类扫描性能和分析相关。



=== BlueXP分类多久扫描一次我的数据？

虽然初始数据扫描可能需要一点时间、但后续扫描只会检查增量更改、从而缩短系统扫描时间。BlueXP分类功能会以循环方式持续扫描数据、一次扫描六个存储库、以便快速对所有更改过的数据进行分类。

link:task-scanning-overview.html["了解扫描的工作原理"](英文)

BlueXP  分类每天只扫描一次数据库；数据库不会像其他数据源一样连续扫描。

数据扫描对存储系统和数据的影响可以忽略不计。



=== 扫描性能是否有所不同？

扫描性能可能因网络带宽和环境中的平均文件大小而异。它还可能取决于主机系统（在云端或内部）的大小特征。有关详细信息、请参见 link:concept-cloud-compliance.html["BlueXP分类实例"] 和 link:task-deploy-overview.html["正在部署BlueXP分类"] 。

首次添加新数据源时、您还可以选择仅执行"映射"(仅限映射)扫描、而不执行完整的"分类"(映射和分类)扫描。由于无法访问文件以查看数据源中的数据，因此可以非常快速地对数据源进行映射。link:task-scanning-overview.html["查看映射扫描与分类扫描之间的区别"](英文)



=== 是否可以使用BlueXP分类搜索数据？

BlueXP分类提供了广泛的搜索功能、使您可以轻松搜索所有连接源中的特定文件或数据片段。BlueXP分类使用户能够更深入地搜索元数据所反映的内容。它是一种不受语言限制的服务、还可以读取文件并分析多种敏感数据类型、例如名称和ID。例如、用户可以在结构化数据存储和非结构化数据存储之间进行搜索、以查找可能违反公司策略从数据库泄漏到用户文件的数据。可以保存搜索以供日后使用、也可以创建策略以按设置的频率搜索结果并对结果执行操作。

找到感兴趣的文件后、可以列出相关特征、包括标记、工作环境帐户、存储分段、文件路径、 类别(来自分类)、文件大小、上次修改、权限状态、重复、 敏感度级别、个人数据、文件中的敏感数据类型、所有者、文件类型、文件大小、创建时间、 文件哈希、数据是否已分配给需要关注的人员等。筛选器可用于筛选与此无关的特征。

BlueXP  分类还具有基于角色的访问控制(Role-Based Access Control、RBAC)、可在具有适当权限的情况下移动或删除文件。如果不存在适当的权限、则可以将任务分配给组织中拥有适当权限的人员。



== BlueXP分类管理和隐私

以下问题提供了有关如何管理BlueXP分类和隐私设置的信息。



=== 如何启用或禁用BlueXP  分类？

首先、您需要在BlueXP中或内部系统上部署BlueXP分类实例。实例运行后，您可以从*Configuration*选项卡或通过选择特定的工作环境在现有工作环境、数据库和其他数据源上启用该服务。link:task-getting-started-compliance.html["了解如何开始使用"](英文)


NOTE: 在数据源上激活BlueXP分类会立即执行初始扫描。扫描结果会在之后不久显示。

您可以从"BlueXP分类配置"页面中禁用BlueXP分类、使其无法扫描单个工作环境、数据库或文件共享组。请参阅。 link:task-managing-compliance.html["从BlueXP分类中删除数据源"]

要完全删除BlueXP分类实例、您可以从云提供商的门户或内部位置手动删除BlueXP分类实例。



=== 服务是否可以排除某些目录中的扫描数据？

是。如果希望BlueXP分类排除驻留在特定数据源目录中的扫描数据、则可以将该列表提供给分类引擎。应用此更改后、BlueXP分类将排除指定目录中的扫描数据。link:task-exclude-scan-paths.html["了解更多信息。"](英文)



=== 是否已扫描驻留在ONTAP卷上的快照？

不会。BlueXP  分类不会扫描快照、因为其内容与卷中的内容相同。



=== 如果在 ONTAP 卷上启用了数据分层，会发生什么情况？

当BlueXP  分类使用"仅映射"扫描将冷数据分层到对象存储的卷时、它会扫描所有数据—本地磁盘上的数据以及分层到对象存储的冷数据。实施分层的非NetApp产品也是如此。

"仅映射"扫描不会加热冷数据、它会保持冷数据并保留在对象存储中。另一方面、如果执行地图和分类扫描、某些配置可能会加热冷数据。



== 源系统的类型和数据类型

以下问题与可扫描的存储类型以及所扫描的数据类型有关。



=== 在政府区域部署时是否存在任何限制？

如果Connector部署在政府区域(AWS GovCloud、Azure Gov或Azure DoD)中、则支持BlueXP分类、也称为"受限模式"。



=== 如果在无法访问Internet的站点上安装BlueXP分类、则可以扫描哪些数据源？

BlueXP分类只能扫描内部站点本地数据源中的数据。此时、BlueXP分类可以在"专用模式"(也称为"非公开"站点)下扫描以下本地数据源：

* 内部部署 ONTAP 系统
* 数据库架构
* 使用简单存储服务（ S3 ）协议的对象存储


请参阅。 link:concept-cloud-compliance.html["支持的工作环境和数据源"]



=== 支持哪些文件类型？

BlueXP分类会扫描所有文件以查看类别和元数据洞察力、并在信息板的文件类型部分中显示所有文件类型。

当BlueXP分类检测到个人身份信息(PII)或执行DSAR搜索时、仅支持以下文件格式：

`+.CSV, .DCM, .DICOM, .DOC, .DOCX, .JSON, .PDF, .PPTX, .RTF, .TXT, .XLS, .XLSX, Docs, Sheets, and Slides+`



=== BlueXP分类可捕获哪些类型的数据和元数据？

通过BlueXP分类、您可以对数据源运行常规"映射"扫描或完整的"分类"扫描。映射仅提供数据的概览，而 " 分类 " 则提供数据的深度扫描。由于无法访问文件以查看数据源中的数据，因此可以非常快速地对数据源进行映射。

* *数据映射扫描(仅映射扫描)*：BlueXP  分类仅扫描元数据。这对于整体数据管理和监管、快速的项目范围界定、非常大的资产和优先级排序非常有用。数据映射基于元数据、被视为*快速*扫描。
+
快速扫描后、您可以生成数据映射报告。本报告概述了存储在企业数据源中的数据、可帮助您确定资源利用率、迁移、备份、安全性和合规性流程。

* *数据分类深度扫描(地图和分类扫描)*：在整个环境中使用标准协议和只读权限进行BlueXP  分类扫描。系统会打开并扫描选定文件、以查看与业务相关的敏感数据、私有信息以及与勒索软件相关的问题。
+
完成完整扫描后、您可以对数据应用许多其他BlueXP分类功能、例如在"数据调查"页面中查看和细化数据、在文件中搜索名称、复制、移动和删除源文件等。



BlueXP分类可捕获元数据、例如：文件名、权限、创建时间、上次访问和上次修改。这包括"数据调查"面页和"数据调查报告"中显示的所有元数据。

BlueXP  分类可以识别多种类型的私有数据、例如个人信息(Pii)和敏感个人信息(SPII)。有关私有数据的详细信息，请参见 https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["BlueXP分类扫描的私有数据的类别"]。



=== 是否可以将BlueXP分类信息限制为特定用户？

是的、BlueXP分类与BlueXP完全集成。BlueXP  用户只能查看其根据权限有资格查看的工作环境的信息。

此外，如果要允许某些用户只查看BlueXP  分类扫描结果而不管理BlueXP  分类设置，则可以为这些用户分配*Classification viewer*角色(在标准模式下使用BlueXP  时)或*Compliance Viewer*角色(在受限模式下使用BlueXP  时)。link:concept-cloud-compliance.html["了解更多信息。"](英文)



=== 任何人都可以访问在我的浏览器和BlueXP分类之间发送的私有数据吗？

不可以。您的浏览器和BlueXP  分类实例之间发送的私有数据会通过TLS 1.2进行端到端加密来保护、这意味着NetApp和非NetApp方无法读取这些数据。除非您申请并批准访问权限、否则BlueXP分类不会与NetApp共享任何数据或结果。

扫描的数据会保留在您的环境中。



=== 如何处理敏感数据？

NetApp无法访问敏感数据、也不会在UI中显示这些数据。敏感数据会被屏蔽、例如、信用卡信息会显示最后四个数字。



=== 数据存储在何处？

扫描结果存储在BlueXP分类实例中的ElancSearch中。



=== 如何访问数据？

BlueXP分类可通过API调用访问存储在El路径 搜索中的数据、API调用需要进行身份验证、并使用AES-128进行加密。要访问El路径 搜索、直接需要root访问权限。



== 许可证和成本

以下问题与使用BlueXP分类的许可和成本有关。



=== BlueXP分类的成本是多少？

BlueXP分类是BlueXP的核心功能、不收费。



== 连接器部署

以下问题与BlueXP Connector相关。



=== 什么是连接器？

Connector是在您的云帐户或内部环境中的计算实例上运行的软件、可使BlueXP安全地管理云资源。要使用BlueXP分类、您必须部署Connector。



=== 连接器需要安装在何处？

扫描数据时、需要将BlueXP  连接器安装在以下位置：

* 对于AWS中的Cloud Volumes ONTAP或Amazon FSx for ONTAP：Connector位于AWS中。
* 对于Azure或Azure NetApp Files中的Cloud Volumes ONTAP：Connector位于Azure中。
* 对于GCP中的Cloud Volumes ONTAP：连接器位于GCP中。
* 对于内部ONTAP系统：Connector位于内部。


如果这些位置有数据，则可能需要使用 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#when-to-use-multiple-connectors["多个连接器"^]。



=== BlueXP分类是否需要访问凭据？

BlueXP分类本身不会检索存储凭据。而是存储在BlueXP Connector中。

BlueXP分类使用数据平面凭据、例如CIFS凭据在扫描前挂载共享。



=== 服务和连接器之间的通信是否使用HTTP？

是的、BlueXP分类使用HTTP与BlueXP Connector进行通信。



== BlueXP分类部署

以下问题与单独的BlueXP分类实例相关。



=== BlueXP分类支持哪些部署模式？

借助BlueXP、用户几乎可以在任何位置扫描和报告系统、包括内部环境、云和混合环境。BlueXP分类通常使用SaaS模式进行部署、在该模式中、服务通过BlueXP界面启用、无需安装硬件或软件。即使在这种即点即用的部署模式下、无论数据存储是在内部还是在公有 云中、都可以进行数据管理。



=== BlueXP分类需要哪种类型的实例或VM？

时间link:task-deploy-cloud-compliance.html["部署在云中"]：

* 在AWS中、BlueXP分类在具有500 GiB GP2磁盘的m6i.4x大型 实例上运行。您可以在部署期间选择较小的实例类型。
* 在Azure中、BlueXP分类在具有500 GiB磁盘的Standard" D16s_v3虚拟机上运行。
* 在GCP中、BlueXP分类在具有500 GiB标准永久性磁盘的n2-standard-16虚拟机上运行。


link:concept-cloud-compliance.html["详细了解BlueXP分类的工作原理"](英文)



=== 是否可以在自己的主机上部署BlueXP分类？

是。您可以在可通过网络或云访问Internet的Linux主机上安装BlueXP分类软件。一切都运行正常、您可以继续通过BlueXP管理扫描配置和结果。有关系统要求和安装详细信息、请参见link:task-deploy-compliance-onprem.html["在内部部署BlueXP分类"]。



=== 没有Internet访问的安全站点如何？

是的、这一点也受支持。您可以link:task-deploy-compliance-dark-site.html["在无法访问Internet的内部站点中部署BlueXP分类"]访问完全安全的站点。
