---
sidebar: sidebar 
permalink: faq-cloud-compliance.html 
keywords: faq, frequently asked questions, questions, cloud compliance, data sense 
summary: 如果您只是想快速了解问题解答，此常见问题解答会很有帮助。 
---
= 有关BlueXP分类的常见问题
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您只是想快速了解问题解答，此常见问题解答会很有帮助。



== BlueXP分类服务

以下问题概括说明了BlueXP分类。



=== 什么是BlueXP分类？

BlueXP分类是一种云产品、它使用人工智能(AI)驱动的技术帮助您了解数据环境并识别存储系统中的敏感数据。这些系统可以是您已添加到BlueXP Canvas中的工作环境、也可以是BlueXP分类可通过网络访问的多种类型的数据源。 link:faq-cloud-compliance.html#what-sources-of-data-can-be-scanned-with-bluexp-classification["请参见下面的完整列表"]。

BlueXP分类提供了预定义的参数(例如敏感信息类型和类别)、以满足有关数据隐私和敏感性的新数据合规性法规、例如GDPR、CCPA、HIPAA等。



=== BlueXP分类的工作原理是什么？

BlueXP分类可在BlueXP系统和存储系统的旁边部署另一层人工智能。然后、它会扫描卷、分段、数据库和其他存储帐户上的数据、并为找到的数据洞察力编制索引。BlueXP分类利用人工智能和自然语言处理、而不是通常围绕正则表达式和模式匹配构建的替代解决方案。

BlueXP分类使用AI提供对数据的上下文了解、以实现准确的检测和分类。它由AI驱动、因为它专为现代数据类型和规模而设计。它还了解数据环境、以便提供强大、准确的发现和分类。

link:concept-cloud-compliance.html["详细了解BlueXP分类的工作原理"^]。



=== BlueXP分类的常见用例有哪些？

* 识别个人身份信息（ PiII ）。
* 根据 GDPR ， CCPA ， HIPAA 和其他数据隐私法规的要求，根据数据主题轻松查找和报告特定数据。
* 遵守新的和即将出台的数据隐私法规。
* 遵守数据合规性和隐私法规。
* 将数据从传统系统迁移到云。
* 遵守数据保留策略。


https://bluexp.netapp.com/netapp-cloud-data-sense["详细了解BlueXP分类的用例"^]。



=== BlueXP分类的架构如何？

BlueXP分类可在云端或内部部署一个服务器或集群、无论您选择在何处。这些服务器通过标准协议连接到数据源、并为Elasticsearch集群中的结果编制索引、该集群也部署在相同的服务器上。这样可以支持多云、跨云、私有云和内部环境。



=== 支持哪些云提供商？

BlueXP分类作为BlueXP的一部分运行、并支持AWS、Azure和GCP。这样，您的组织就可以在不同的云提供商之间实现统一的隐私可见性。



=== BlueXP分类是否具有REST API？是否可与第三方工具配合使用？

BlueXP支持其服务的REST API功能。如果BlueXP不是首选管理点、则也可以通过REST API使用BlueXP分类等服务。每个用户操作都有一个可与第三方系统集成的REST API。



=== BlueXP分类是否可通过商城获得？

是的、BlueXP和BlueXP分类可从AWS、Azure和GCP市场获得。



== BlueXP分类扫描和分析

以下问题与用户可用的BlueXP分类扫描性能和分析相关。



=== BlueXP分类多久扫描一次我的数据？

虽然初始数据扫描可能需要一点时间、但后续扫描只会检查增量更改、从而缩短系统扫描时间。BlueXP分类功能会以循环方式持续扫描数据、一次扫描六个存储库、以便快速对所有更改过的数据进行分类。

link:concept-cloud-compliance.html#how-scans-work["了解扫描的工作原理"]。

请注意、BlueXP分类每天只扫描一次数据库-数据库不会像其他数据源一样连续扫描。

数据扫描对存储系统和数据的影响可以忽略不计。但是、如果您担心的影响非常小、则可以将BlueXP分类配置为执行"慢速"扫描。 link:task-reduce-scan-speed.html["请参见如何降低扫描速度"]。



=== 是否可以使用BlueXP分类搜索数据？

BlueXP分类提供了广泛的搜索功能、使您可以轻松搜索所有连接源中的特定文件或数据片段。BlueXP分类使用户能够更深入地搜索元数据所反映的内容。它是一种不受语言限制的服务、还可以读取文件并分析多种敏感数据类型、例如名称和ID。例如、用户可以在结构化数据存储和非结构化数据存储之间进行搜索、以查找可能违反公司策略从数据库泄漏到用户文件的数据。可以保存搜索以供日后使用、也可以创建策略以按设置的频率搜索结果并对结果执行操作。

找到感兴趣的文件后、可以列出相关特征、包括标记、工作环境帐户、存储分段、文件路径、 类别(来自分类)、文件大小、上次修改、权限状态、重复、 敏感度级别、个人数据、文件中的敏感数据类型、所有者、文件类型、文件大小、创建时间、 文件哈希、数据是否已分配给需要关注的人员等。筛选器可用于筛选与此无关的特征。BlueXP分类还具有RBAC控件、允许在具有适当权限的情况下移动或删除文件。如果不存在适当的权限、则可以将任务分配给组织中拥有适当权限的人员。



=== BlueXP分类提供哪种分析？

可以直观地表示数据源、并以图形方式定义和描述关系。例如、管理员可以查看整个企业内数据源(内部系统、数据库、文件共享、S3存储、OneDrive、 等)。然后、他们可以复制、移动、删除和管理数据、以优化存储成本并降低风险。用户可以通过查看哪些敏感数据可能会公开来降低风险、并且可以创建作业来管理权限以实现强大的数据保护。BlueXP分类还会对所有不同类型的数据进行分类、因此管理员可以按类型调查数据、并查看对数据执行了哪些操作以及何时执行。



=== BlueXP分类是否提供报告？

是的。BlueXP分类提供的信息可能与组织中的其他利益相关方相关、因此我们可以帮助您生成报告以分享见解。以下报告可用于BlueXP分类：

隐私风险评估报告:: 根据您的数据提供隐私洞察力并获得隐私风险得分。 link:task-generating-compliance-reports.html#privacy-risk-assessment-report["了解更多信息。"^]。
数据主体访问请求报告:: 用于提取包含数据主体的特定名称或个人标识符相关信息的所有文件的报告。 link:task-generating-compliance-reports.html#what-is-a-data-subject-access-request["了解更多信息。"^]。
PCI DSS 报告:: 帮助您确定信用卡信息在整个文件中的分布情况。 link:task-generating-compliance-reports.html#pci-dss-report["了解更多信息。"^]。
HIPAA 报告:: 帮助您确定运行状况信息在文件中的分布情况。 link:task-generating-compliance-reports.html#hipaa-report["了解更多信息。"^]。
数据映射报告:: 提供有关工作环境中文件大小和数量的信息。其中包括使用容量，数据期限，数据大小和文件类型。 link:task-controlling-governance-data.html#data-mapping-report["了解更多信息。"^]。
数据发现评估报告:: 对扫描的环境进行高级别分析、以突出显示系统的发现结果、并显示关注领域和可能的修复步骤。 link:task-controlling-governance-data.html#data-discovery-assessment-report["学习模式"^]。
报告特定信息类型:: 我们提供的报告包含有关包含个人数据和敏感个人数据的已识别文件的详细信息。您还可以查看按类别和文件类型细分的文件。 link:task-controlling-private-data.html["了解更多信息。"^]。




=== 扫描性能是否有所不同？

扫描性能可能因网络带宽和环境中的平均文件大小而异。它还可能取决于主机系统（在云端或内部）的大小特征。请参见 link:concept-cloud-compliance.html#the-bluexp-classification-instance["BlueXP分类实例"^] 和 link:task-deploy-cloud-compliance.html["正在部署BlueXP分类"^] 有关详细信息 ...

在首次添加新数据源时，您还可以选择仅执行 " 映射 " 扫描，而不是执行完整的 " 分类 " 扫描。由于无法访问文件以查看数据源中的数据，因此可以非常快速地对数据源进行映射。 link:concept-cloud-compliance.html#whats-the-difference-between-mapping-and-classification-scans["查看映射扫描与分类扫描之间的区别"^]。



== BlueXP分类管理和隐私

以下问题提供了有关如何管理BlueXP分类和隐私设置的信息。



=== 如何启用BlueXP分类？

首先、您需要在BlueXP中或内部系统上部署BlueXP分类实例。实例运行后，您可以从*Configuration*选项卡或通过选择特定的工作环境在现有工作环境、数据库和其他数据源上启用该服务。

link:task-getting-started-compliance.html["了解如何开始使用"^]。


NOTE: 在数据源上激活BlueXP分类会立即执行初始扫描。扫描结果会在之后不久显示。



=== 如何禁用BlueXP分类？

您可以从"BlueXP分类配置"页面中禁用BlueXP分类、以便扫描单个工作环境、数据库、文件共享组、OneDrive帐户或SharePoint帐户。

link:task-managing-compliance.html["了解更多信息。"^]。


NOTE: 要完全删除BlueXP分类实例、您可以从云提供商的门户或内部位置手动删除BlueXP分类实例。



=== 我是否可以根据组织的需求自定义服务？

BlueXP分类可提供开箱即用的数据洞察力。您可以根据组织的需求提取和利用这些洞察信息。

此外、BlueXP分类还提供了多种方法来添加BlueXP分类将在扫描中识别的自定义"个人数据"列表、从而为您提供有关组织的_all_文件中潜在敏感数据所在位置的完整信息。

* 您可以根据要扫描的数据库中的特定列添加唯一标识符—我们称之为*数据Fusion *。
* 您可以从文本文件添加自定义关键字。
* 您可以使用正则表达式(regex)添加自定义模式。


link:task-managing-data-fusion.html["了解更多信息。"^]。



=== 是否可以将BlueXP分类信息限制为特定用户？

是的、BlueXP分类与BlueXP完全集成。BlueXP用户只能根据其工作空间权限查看其有资格查看的工作环境的信息。

此外、如果要允许某些用户仅查看BlueXP分类扫描结果而不管理BlueXP分类设置、则可以为这些用户分配云合规性查看器角色。

link:concept-cloud-compliance.html#user-access-to-compliance-information["了解更多信息。"^]。



=== 任何人都可以访问在我的浏览器和BlueXP分类之间发送的私有数据吗？

否在您的浏览器和BlueXP分类实例之间发送的私有数据会通过端到端加密进行保护、这意味着NetApp和第三方无法读取这些数据。除非您申请并批准访问权限、否则BlueXP分类不会与NetApp共享任何数据或结果。



=== 如果在 ONTAP 卷上启用了数据分层，会发生什么情况？

当BlueXP分类扫描冷数据分层到对象存储的卷时、它会扫描所有数据—本地磁盘上的数据以及分层到对象存储的冷数据。实施分层的非NetApp产品也是如此。

扫描不会加热冷数据—它会保持冷状态并保留在对象存储中。



=== BlueXP分类是否可以向我的组织发送通知？

是的。在策略返回结果时、与策略功能结合使用、您可以向BlueXP用户(每日、每周或每月)或任何其他电子邮件地址发送电子邮件警报、以便您可以获得保护数据的通知。了解更多信息 link:task-using-policies.html["策略"^]。

您还可以从 " 监管 " 页面和 " 调查 " 页面下载状态报告，并在组织内部共享这些报告。



=== BlueXP分类是否可以与我在文件中嵌入的AIP标签配合使用？

是的。如果您订阅了BlueXP分类正在扫描的文件、则可以管理这些文件中的AIP标签 https://azure.microsoft.com/en-us/services/information-protection/["Azure 信息保护（ AIP ）"^]。您可以查看已分配给文件的标签，向文件添加标签以及更改现有标签。

link:task-org-private-data.html#categorizing-your-data-using-aip-labels["了解更多信息。"^]。



== 源系统的类型和数据类型

以下问题与可扫描的存储类型以及所扫描的数据类型有关。



=== 可以使用BlueXP分类扫描哪些数据源？

BlueXP分类可以扫描您添加到BlueXP Canvas中的工作环境中的数据、以及BlueXP分类可以通过网络访问的多种结构化和非结构化数据源中的数据。

* 工作环境： *

* Cloud Volumes ONTAP （部署在 AWS ， Azure 或 GCP 中）
* 内部 ONTAP 集群
* Azure NetApp Files
* 适用于 ONTAP 的 Amazon FSX
* Amazon S3


* 数据源： *

* 非 NetApp 文件共享
* 对象存储（使用 S3 协议）
* 数据库(Amazon RDS、MongoDB、MySQL、Oracle、PostgreSQL、 SAP HANA、SQL Server)
* OneDrive 帐户
* SharePoint Online和内部部署帐户
* Google Drive帐户


BlueXP分类支持NFS 3.x、4.0和4.1以及CIFS 1.x、2.0、2.1和3.0。



=== 在政府区域部署时是否存在任何限制？

如果Connector部署在政府区域(AWS GovCloud、Azure Gov或Azure DoD)中、则支持BlueXP分类、也称为"受限模式"。以这种方式部署时、BlueXP分类具有以下限制：

* 无法扫描OneDrive帐户、SharePoint帐户和Google Drive帐户。
* 无法集成Microsoft Azure信息保护(AIP)标签功能。




=== 如果在无法访问Internet的站点上安装BlueXP分类、则可以扫描哪些数据源？

BlueXP分类只能扫描内部站点本地数据源中的数据。此时、BlueXP分类可以在"专用模式"(也称为"非公开"站点)下扫描以下本地数据源：

* 内部部署 ONTAP 系统
* 数据库架构
* SharePoint内部部署帐户(SharePoint Server)
* 非 NetApp NFS 或 CIFS 文件共享
* 使用简单存储服务（ S3 ）协议的对象存储




=== 支持哪些文件类型？

BlueXP分类会扫描所有文件以查看类别和元数据洞察力、并在信息板的文件类型部分中显示所有文件类型。

当BlueXP分类检测到个人身份信息(PII)或执行DSAR搜索时、仅支持以下文件格式：

`+.CSV、.dcm、.Dicom、.DOC、.docx、 .json、.PDF、.PPTX、.RTV、.TXT、 .XLS、.XLSX、文档、工作表和幻灯片+`



=== BlueXP分类可捕获哪些类型的数据和元数据？

通过BlueXP分类、您可以对数据源运行常规"映射"扫描或完整的"分类"扫描。映射仅提供数据的概览，而 " 分类 " 则提供数据的深度扫描。由于无法访问文件以查看数据源中的数据，因此可以非常快速地对数据源进行映射。

* 数据映射扫描。
+
BlueXP分类仅扫描元数据。这对于整体数据管理和监管、快速的项目范围界定、非常大的资产和优先级排序非常有用。数据映射基于元数据、被视为*快速*扫描。

+
快速扫描后、您可以生成数据映射报告。本报告概述了存储在企业数据源中的数据、可帮助您确定资源利用率、迁移、备份、安全性和合规性流程。

* 数据分类(深度)扫描。
+
BlueXP分类扫描在整个环境中使用标准协议和只读权限。系统会打开并扫描选定文件、以查看与业务相关的敏感数据、私有信息以及与勒索软件相关的问题。

+
完成完整扫描后、您可以对数据应用许多其他BlueXP分类功能、例如在"数据调查"页面中查看和细化数据、在文件中搜索名称、复制、移动和删除源文件等。





== 许可证和成本

以下问题与使用BlueXP分类的许可和成本相关。



=== BlueXP分类的成本是多少？

使用BlueXP分类的成本取决于要扫描的数据量。BlueXP分类在BlueXP工作空间中扫描的前1 TB数据可免费使用30天。达到任一限制后、您需要执行以下操作之一才能继续扫描数据：

* 您的云提供商或订阅了BlueXP Marketplace列表
* NetApp自带许可证(BYOL)


请参见 https://bluexp.netapp.com/pricing["定价"^] 了解详细信息。



=== 如果我已达到BYOL容量限制、会发生什么情况？

如果达到BYOL容量限制、BlueXP分类仍会继续运行、但对信息板的访问会被阻止、因此您无法查看有关任何扫描数据的信息。如果您希望减少要扫描的卷数量、从而可能使容量使用量低于许可证限制、则只能使用配置页面。您必须续订BYOL许可证才能重新获得对BlueXP分类的完全访问权限。



== 连接器部署

以下问题与BlueXP Connector相关。



=== 什么是连接器？

Connector是在您的云帐户或内部环境中的计算实例上运行的软件、可使BlueXP安全地管理云资源。要使用BlueXP分类、您必须部署Connector。



=== 连接器需要安装在何处？

* 在 AWS 中的 Cloud Volumes ONTAP ，适用于 ONTAP 的 Amazon FSx 或 AWS S3 存储分段中扫描数据时，您可以使用 AWS 中的连接器。
* 在 Azure 或 Azure NetApp Files 中的 Cloud Volumes ONTAP 中扫描数据时，您可以使用 Azure 中的连接器。
* 在 GCP 的 Cloud Volumes ONTAP 中扫描数据时，您可以在 GCP 中使用连接器。
* 在扫描内部ONTAP 系统、非NetApp文件共享、通用S3对象存储、数据库、OneDrive文件夹、SharePoint帐户和Google Drive帐户中的数据时、您可以在任何这些云位置使用连接器。


因此、如果您在其中许多位置都有数据、则可能需要使用 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#when-to-use-multiple-connectors["多个连接器"^]。



=== 是否可以在自己的主机上部署此连接器？

是的。您可以 https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["在内部部署 Connector"^] 在网络中的Linux主机或云中的主机上。如果您计划在内部部署BlueXP分类、则可能还需要在内部安装Connector、但这不是必需的。



=== 没有Internet访问的安全站点如何？

是的、这一点也受支持。您可以 https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["在无法访问Internet的内部Linux主机上部署Connector"^]。 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["这也称为"专用模式""^]。然后、您可以发现内部ONTAP 集群和其他本地数据源、并使用BlueXP分类扫描数据。



== BlueXP分类部署

以下问题与单独的BlueXP分类实例相关。



=== BlueXP分类支持哪些部署模式？

借助BlueXP、用户几乎可以在任何位置扫描和报告系统、包括内部环境、云和混合环境。BlueXP分类通常使用SaaS模式进行部署、在该模式中、服务通过BlueXP界面启用、无需安装硬件或软件。即使在这种即点即用的部署模式下、无论数据存储是在内部还是在公有 云中、都可以进行数据管理。



=== BlueXP分类需要哪种类型的实例或VM？

时间 link:task-deploy-cloud-compliance.html["部署在云中"]：

* 在AWS中、BlueXP分类在具有500 GiB GP2磁盘的m6i.4x大型 实例上运行。您可以在部署期间选择较小的实例类型。
* 在Azure中、BlueXP分类在具有500 GiB磁盘的Standard" D16s_v3虚拟机上运行。
* 在GCP中、BlueXP分类在具有500 GiB标准永久性磁盘的n2-standard-16虚拟机上运行。


请注意、您可以在CPU较少、RAM较少的系统上部署BlueXP分类、但使用这些系统时存在一些限制。请参见 link:concept-cloud-compliance.html#using-a-smaller-instance-type["使用较小的实例类型"] 了解详细信息。

link:concept-cloud-compliance.html["详细了解BlueXP分类的工作原理"^]。



=== 是否可以在自己的主机上部署BlueXP分类？

是的。您可以在可通过网络或云访问Internet的Linux主机上安装BlueXP分类软件。一切都运行正常、您可以继续通过BlueXP管理扫描配置和结果。请参见 link:task-deploy-compliance-onprem.html["在内部部署BlueXP分类"] 了解系统要求和安装详细信息。



=== 没有Internet访问的安全站点如何？

是的、这一点也受支持。您可以 link:task-deploy-compliance-dark-site.html["在无法访问Internet的内部站点中部署BlueXP分类"] 适用于完全安全的站点。
