---
sidebar: sidebar 
permalink: task-deploy-overview.html 
keywords: cloud compliance, data sense, get started, deploy cloud data sense, outbound internet, endpoints, cloud compliance internet, web browser connectivity, cloud compliance access, privacy, compliance, bluexp classification 
summary: 规划满足您需求的BlueXP分类部署。 
---
= 您应使用哪种BlueXP分类部署？
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以通过不同方式部署BlueXP分类。了解哪种方法符合您的需求。

BlueXP分类可通过以下方式部署：

* link:task-deploy-cloud-compliance.html["使用BlueXP在云中部署"](英文)BlueXP将在与BlueXP Connector相同的云提供商网络中部署BlueXP分类实例。
* link:task-deploy-compliance-onprem.html["在可访问Internet的Linux主机上安装"](英文)在网络中的Linux主机或云中可访问Internet的Linux主机上安装BlueXP分类。如果您希望使用同时位于内部的BlueXP分类实例扫描内部ONTAP系统、则此类安装可能是一个不错的选择、但这不是一项要求。
* link:task-deploy-compliance-dark-site.html["在内部站点的Linux主机上安装、无需访问Internet"]也称为_private模式。_此类安装使用安装脚本、无法连接到BlueXP  SaaS层。


可以访问Internet的Linux主机上的安装以及不能访问Internet的Linux主机上的内部安装都使用安装脚本。该脚本首先会检查系统和环境是否满足前提条件。如果满足这些前提条件、安装将开始。如果要独立于运行BlueXP分类安装来验证前提条件、则可以下载一个单独的软件包、该软件包仅测试前提条件。

请参阅 link:task-test-linux-system.html["检查Linux主机是否已准备好安装BlueXP分类"]。
