---
sidebar: sidebar 
permalink: task-audit-data-sense-actions.html 
keywords: compliance, actions, view progress, audit, logs, installation 
summary: BlueXP分类可记录对BlueXP分类正在扫描的所有工作环境和数据源中的文件执行的管理活动。BlueXP分类还会记录部署BlueXP分类实例时的活动。 
---
= 审核BlueXP分类操作的历史记录
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP分类可记录对BlueXP分类正在扫描的所有工作环境和数据源中的文件执行的管理活动。BlueXP分类还会记录部署BlueXP分类实例时的活动。

您可以查看BlueXP分类审核日志文件的内容、也可以下载这些文件、以查看发生了哪些文件更改以及更改的时间。例如、您可以查看发出的请求、请求的时间以及详细信息、例如删除文件时的源位置或移动文件时的源和目标位置。


NOTE: 此信息仅与BlueXP  分类原有版本1.3及更早版本相关。



== 日志文件内容

审核日志中的每一行都包含以下格式的信息：

`<full date> | <status> | ds_audit_logger | <module> | 0 | 0 | File <full file path> deleted from device <device path> - <result>`

* date and time—事件的完整时间戳
* status—信息、警告
* 操作类型(删除、复制、移动、创建保存的搜索、更新保存的搜索、重新扫描文件、下载JSON报告等)
* 文件名(如果操作与文件相关)
* 操作的详细信息—已执行的操作：取决于操作
+
** 保存的搜索名称
** for move—源和目标
** 对于copy—源和目标
** 标记-标记名称
** 用于assign to—用户名
** 对于电子邮件警报—电子邮件地址/帐户




例如、日志文件中的以下行显示复制操作成功、复制操作失败。

....
2022-06-06 15:23:08,910 | INFO | ds_audit_logger | es_scanned_file | 237 | 49 | Copy file /CIFS_share/data/dop1/random_positives.tsv from device 10.31.133.183 (type: SMB_SHARE) to device 10.31.130.133:/export_reports (NFS_SHARE) - SUCCESS
2022-06-06 15:23:08,968 | WARNING | ds_audit_logger | es_scanned_file | 239 | 153 | Copy file /CIFS_share/data/compliance-netapp.tar.gz from device 10.31.133.183 (type: SMB_SHARE) to device 10.31.130.133:/export_reports (NFS_SHARE) - FAILURE
....


== 日志文件位置

管理审核日志文件位于BlueXP  分类计算机的以下位置： `/opt/netapp/audit_logs/`

安装审核日志文件将写入其中 `/opt/netapp/install_logs/`

每个日志文件的大小最多可以为10 MB。达到此限制后、将启动一个新的日志文件。这些日志文件名为"DataSICE_AUDIST.LOG_"、"DataSICE_AUDULT_LOG_1"、"DataSICE_AUDIST_LOG.2"等。系统中最多保留100个日志文件-达到最大值后、较早的日志文件将自动删除。



== 访问日志文件

您需要登录BlueXP分类系统才能访问日志文件。根据您是在Linux计算机上手动安装软件还是在云中部署了实例、了解如何link:reference-log-in-to-instance.html["登录到BlueXP分类系统"]。
