---
sidebar: sidebar 
permalink: task-audit-data-sense-actions.html 
keywords: compliance, actions, view progress, audit, logs, installation 
summary: Data sense会记录对Data sense正在扫描的所有工作环境和数据源中的文件执行的管理活动。Data sense还会记录部署Data sense实例时的活动。 
---
= 审核数据感知操作的历史记录
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Data sense会记录对Data sense正在扫描的所有工作环境和数据源中的文件执行的管理活动。Data sense还会记录部署Data sense实例时的活动。

您可以查看Data sense审核日志文件的内容、也可以下载这些内容、以查看发生了哪些文件更改以及何时发生更改。例如、您可以查看发出的请求、请求的时间以及详细信息、例如删除文件时的源位置或移动文件时的源和目标位置。



== 日志文件内容

审核日志中的每一行都包含以下格式的信息：

`<full date> | <status> | ds_audit_logger | <module> | 0 | 0 | File <full file path> deleted from device <device path> - <result>`

* date and time—事件的完整时间戳
* status—信息、警告
* 操作类型(删除、复制、移动、创建策略、更新策略、 重新扫描文件、下载JSON报告等)
* 文件名(如果操作与文件相关)
* 操作的详细信息—已执行的操作：取决于操作
+
** Policy name
** for move—源和目标
** 对于copy—源和目标
** 标记-标记名称
** 用于assign to—用户名
** 对于电子邮件警报—电子邮件地址/帐户




例如、日志文件中的以下行显示复制操作成功、复制操作失败。

....
2022-06-06 15:23:08,910 | INFO | ds_audit_logger | es_scanned_file | 237 | 49 | Copy file /CIFS_share/data/dop1/random_positives.tsv from device 10.31.133.183 (type: SMB_SHARE) to device 10.31.130.133:/export_reports (NFS_SHARE) - SUCCESS
2022-06-06 15:23:08,968 | WARNING | ds_audit_logger | es_scanned_file | 239 | 153 | Copy file /CIFS_share/data/compliance-netapp.tar.gz from device 10.31.133.183 (type: SMB_SHARE) to device 10.31.130.133:/export_reports (NFS_SHARE) - FAILURE
....


== 访问日志文件

管理审核日志文件位于Data sense计算机上的： `/opt/netapp/audit_logs/`

安装审核日志文件将写入 `/opt/netapp/install_logs/`

每个日志文件的大小最多可以为10 MB。达到此限制后、将启动一个新的日志文件。这些日志文件名为"DataSICE_AUDIST.LOG_"、"DataSICE_AUDULT_LOG_1"、"DataSICE_AUDIST_LOG.2"等。系统最多保留100个日志文件—达到最大值后、旧日志文件将自动删除。

如果Data sense安装在内部的Linux计算机上或部署在云中的Linux计算机上、则可以直接导航到日志文件。

在云中部署Data sense时、您需要通过SSH连接到Data sense实例。您可以通过输入用户和密码或使用在安装BlueXP Connector期间提供的SSH密钥通过SSH连接到系统。SSH命令为：

 ssh -i <path_to_the_ssh_key> <machine_user>@<datasense_ip>
* <path_to_the_ssh_key>= ssh身份验证密钥的位置
* <machine_user>：
+
** 对于AWS：使用<EC2-user>
** 对于Azure：使用为BlueXP实例创建的用户
** 对于GCP：使用为BlueXP实例创建的用户


* <datasens_ip>=虚拟机实例的IP地址


请注意、您需要修改安全组入站规则才能访问云中的系统。有关详细信息、请参见：

* https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-ports-aws.html["AWS中的安全组规则"^]
* https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-ports-azure.html["Azure中的安全组规则"^]
* https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-ports-gcp.html["Google Cloud中的防火墙规则"^]

