---
sidebar: sidebar 
permalink: task-test-linux-system.html 
keywords: cloud compliance, data sense, get started, deploy cloud BlueXP classification, cloud compliance access, compliance, on-premises, linux, test linux system 
summary: 在Linux主机上手动安装BlueXP分类之前、您可以在此主机上运行一个脚本、以验证是否满足安装BlueXP分类的所有前提条件。您可以在网络中的Linux主机或云中的Linux主机上运行此脚本。主机可以连接到Internet、也可以位于无法访问Internet的站点中。 
---
= 检查Linux主机是否已准备好安装BlueXP分类
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在Linux主机上手动安装BlueXP分类之前、您可以在此主机上运行一个脚本、以验证是否满足安装BlueXP分类的所有前提条件。您可以在网络中的Linux主机或云中的Linux主机上运行此脚本。主机可以连接到Internet、也可以位于无法访问Internet的站点("非公开站点")中。

BlueXP分类安装脚本中还有一个必备测试脚本。此处介绍的脚本专为希望独立于运行BlueXP分类安装脚本来验证Linux主机的用户而设计。



== 入门

您将执行以下任务。

. 如果您尚未安装BlueXP Connector、也可以安装它。您可以在不安装Connector的情况下运行测试脚本、但该脚本会检查Connector与BlueXP分类主机之间的连接、因此建议您使用Connector。
. 准备主机并验证它是否满足所有要求。
. 从BlueXP分类主机启用出站Internet访问。
. 验证是否已在所有系统上启用所有必需的端口。
. 下载并运行前提条件测试脚本。




== 创建连接器

在安装和使用BlueXP分类之前、需要BlueXP Connector。但是、您可以在不使用Connector的情况下运行Prerequisites脚本。

您可以 https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-on-prem.html["在内部安装 Connector"^] 在网络中的Linux主机或云中的Linux主机上。一些计划在本机安装BlueXP分类的用户也可以选择在本机安装Connector。

要在云提供商环境中创建Connector、请参见 https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-aws.html["在 AWS 中创建连接器"^]， https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-azure.html["在 Azure 中创建连接器"^]或 https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-google.html["在 GCP 中创建连接器"^]。

运行Prerequisites脚本时、您需要连接器系统的IP地址或主机名。如果您在内部安装了Connector、则可以获得此信息。如果Connector部署在云中、您可以从BlueXP控制台找到此信息：单击帮助图标、选择*支持*、然后单击*蓝XP连接器*。



== 验证主机要求

BlueXP分类软件必须在满足特定操作系统要求、RAM要求、软件要求等的主机上运行。

* 与其他应用程序共享的主机不支持BlueXP分类-该主机必须是专用主机。
* 在内部构建主机系统时、您可以根据计划进行BlueXP分类扫描的数据集大小在三种系统大小中进行选择。
+
[cols="18,18,26,30"]
|===
| 系统大小 | CPU | RAM (必须禁用交换内存) | Disk 


| *大型* | 16个CPU | 64 GB RAM | 500 GiB SSD位于/、或上
-100 GiB可从/opt获得
-395 GiB可在/var/lib/Docker上使用
/tmp上的5 GiB 


| *中* | 8个CPU | 32 GB RAM | 200 GiB SSD开启/、或
-50 GiB可从/opt获得
-145 GiB可在/var/lib/Docker上使用
/tmp上的5 GiB 


| *小* | 8个CPU | 16 GB RAM | 100 GiB SSD位于/、或上
-50 GiB可从/opt获得
/var/lib/Docker上提供45 GiB
/tmp上的5 GiB 
|===
+
请注意、使用这些较小的系统时存在一些限制。请参见 link:concept-cloud-compliance.html#using-a-smaller-instance-type["使用较小的实例类型"] 了解详细信息。

* 在云中为BlueXP分类安装部署计算实例时、我们建议使用满足上述"大型"系统要求的系统：
+
** * AWS EC2实例类型*：我们建议使用"m6i.4xlarge"。 link:reference-instance-types.html#aws-instance-types["请参见其他AWS实例类型"^]。
** * Azure虚拟机大小*：建议使用"Standard_d16s_v3_"。 link:reference-instance-types.html#azure-instance-types["请参见其他Azure实例类型"^]。
** * GCP计算机类型*：我们建议使用"n2-standard-16"。 link:reference-instance-types.html#gcp-instance-types["请参见其他GCP实例类型"^]。


* *UNIX文件夹权限*：需要以下最低UNIX权限：
+
[cols="25,25"]
|===
| 文件夹 | 最小权限 


| /tmp | `rwxrwxrwt` 


| /opt | `rwxr-xr-x` 


| /var/lib/Docker | `rwx------` 


| /user/lib/systemd/system | `rwxr-xr-x` 
|===
* * 操作系统 * ：
+
** 以下操作系统要求使用Docker容器引擎：
+
*** Red Hat Enterprise Linux 7.8和7.9版- Linux内核版本必须为4.0或更高版本
*** CentOS 7.8和7.9版- Linux内核版本必须为4.0或更高版本
*** Ubuntu 22.04 (需要BlueXP分类版本1.23或更高版本)






* * Red Hat订阅管理*：主机必须向Red Hat订阅管理注册。如果未注册、系统将无法在安装期间访问存储库来更新所需的第三方软件。
* *其他软件*：在安装BlueXP分类之前、必须在主机上安装以下软件：
+
** 根据您使用的操作系统、您需要安装以下容器引擎之一：
+
*** Docker引擎19.3.1或更高版本。 https://docs.docker.com/engine/install/["查看安装说明"^]。
+
https://youtu.be/Ogoufel1q6c["观看此视频"^] 有关在CentOS上安装Docker的快速演示。



** Python 3.6或更高版本。 https://www.python.org/downloads/["查看安装说明"^]。


* * Firewalld注意事项*：如果您计划使用 `firewalld`，我们建议您在安装BlueXP分类之前启用它。运行以下命令进行配置 `firewalld` 以便与BlueXP分类兼容：
+
....
firewall-cmd --permanent --add-service=http
firewall-cmd --permanent --add-service=https
firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --permanent --add-port=8080/tcp
firewall-cmd --permanent --add-port=443/tcp
firewall-cmd --reload
....
+
如果您计划使用其他BlueXP分类主机作为扫描程序节点(在分布式模型中)、请此时将这些规则添加到主系统：

+
....
firewall-cmd --permanent --add-port=2377/tcp
firewall-cmd --permanent --add-port=7946/udp
firewall-cmd --permanent --add-port=7946/tcp
firewall-cmd --permanent --add-port=4789/udp
....
+
请注意、每当启用或更新时、都必须重新启动Docker `firewalld` 设置。





== 从BlueXP分类启用出站Internet访问

BlueXP分类需要出站Internet访问。如果您的虚拟或物理网络使用代理服务器进行Internet访问、请确保BlueXP分类实例具有出站Internet访问权限以联系以下端点。


TIP: 对于安装在无Internet连接站点中的主机系统、不需要此部分。

[cols="43,57"]
|===
| 端点 | 目的 


| https://api.bluexp.netapp.com | 与包括NetApp帐户在内的BlueXP服务进行通信。 


| https://netapp-cloud-account.auth0.com \https://auth0.com | 与BlueXP网站通信以实现集中式用户身份验证。 


| https://support.compliance.api.bluexp.netapp.com/\https://hub.docker.com \https://auth.docker.io \https://registry-1.docker.io \https://index.docker.io/\https://dseasb33srnrn.cloudfront.net/\https://production.cloudflare.docker.com/ | 可用于访问软件映像，清单，模板以及发送日志和指标。 


| https://support.compliance.api.bluexp.netapp.com/ | 使 NetApp 能够从审计记录流化数据。 


| https://github.com/docker \https://download.docker.com | 提供Docker安装的必备软件包。 


| http://mirror.centos.org \http://mirrorlist.centos.org \http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.107-3.el7.noarch.rpm | 提供安装CentOS所需的软件包。 


| \http://packages.ubuntu.com/
\http://archive.ubuntu.com | 提供Ubuntu安装的必备软件包。 
|===


== 验证是否已启用所有必需的端口

您必须确保所有必需的端口均已打开、可供Connector、BlueXP分类、Active Directory和数据源之间进行通信。

[cols="25,25,50"]
|===
| 连接类型 | 端口 | Description 


| 连接器<> BlueXP分类 | 8080 (TCP)、443 (TCP)和80 | 连接器的防火墙或路由规则必须允许通过端口443传入和传出BlueXP分类实例的流量。确保端口8080已打开、以便您可以在BlueXP中查看安装进度。 


| Connector <> ONTAP 集群(NAS) | 443 (TCP)  a| 
BlueXP使用HTTPS发现ONTAP 集群。如果使用自定义防火墙策略、则Connector主机必须允许通过端口443进行出站HTTPS访问。如果Connector位于云中、则预定义的防火墙或路由规则允许所有出站通信。

|===


== 运行BlueXP分类前提条件脚本

按照以下步骤运行BlueXP分类前提条件脚本。

https://youtu.be/_RCYpuLXiV0?si=QLGUw8mqPrz9qs4B["观看此视频"^] 了解如何运行前提条件脚本并解读结果。

.您需要的内容
* 验证您的 Linux 系统是否满足 <<验证主机要求,主机要求>>。
* 确认系统已安装两个必备软件包(Docker引擎和Python 3)。
* 确保您在 Linux 系统上具有 root 权限。


.步骤
. 从下载BlueXP分类前提条件脚本 https://mysupport.netapp.com/site/products/all/details/cloud-data-sense/downloads-tab/["NetApp 支持站点"^]。您应选择的文件名为*独立-前提条件-测试人员-tester-tester*<version>。
. 将文件复制到您计划使用的Linux主机(使用 `scp` 或其他方法)。
. 分配运行脚本的权限。
+
[source, cli]
----
chmod +x standalone-pre-requisite-tester-v1.25.0
----
. 使用以下命令运行此脚本。
+
[source, cli]
----
 ./standalone-pre-requisite-tester-v1.25.0 <--darksite>
----
+
只有在无法访问Internet的主机上运行脚本时、才添加选项"-d暗 站点"。如果主机未连接到Internet、则会跳过某些前提条件测试。

. 该脚本会提示您输入BlueXP分类主机的IP地址。
+
** 输入IP地址或主机名。


. 此脚本将提示您是否已安装BlueXP Connector。
+
** 如果您没有安装Connector、请输入*。
** 如果安装了Connector、请输入*。然后、输入BlueXP Connector的IP地址或主机名、以便测试脚本可以测试此连接。


. 该脚本会在系统上运行各种测试、并在执行过程中显示结果。完成后、它会将会话日志写入名为的文件 `prerequisites-test-<timestamp>.log` 在目录中 `/opt/netapp/install_logs`。


.结果
如果所有前提条件测试均成功运行、则可以在准备就绪后在主机上安装BlueXP分类。

如果发现任何问题、则将其归类为"建议"或"必需"以进行修复。建议的问题通常是会使BlueXP分类扫描和分类任务运行速度变慢的项目。这些项目不需要更正、但您可能需要解决这些问题。

如果存在任何"必需"问题、应修复这些问题并重新运行前提条件测试脚本。
