---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense' 
summary: 了解 Cloud Data sense 中的新增功能。 
---
= Cloud Data sense 的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解 Cloud Data sense 中的新增功能。



== 2023年1月9日(1.19版)



=== 可以查看包含敏感数据且过于宽松的文件图表

"监管"信息板添加了一个新的"敏感数据和宽权限"区域、用于为包含敏感数据(包括敏感和敏感个人数据)且过于宽松的文件提供热图。这样可以帮助您了解敏感数据可能存在哪些风险。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-governance-data.html#data-listed-by-sensitivity-and-wide-permissions["了解更多信息。"]。



=== 数据调查页面提供了三个新筛选器

可以使用新筛选器细化数据调查页面中显示的结果：

* "Number of users with access"筛选器显示了哪些文件和文件夹对一定数量的用户开放。您可以选择一个数字范围来细化结果、例如、查看51-100个用户可访问哪些文件。
* 现在、"创建时间"、"发现时间"、"上次修改时间"和"上次访问时间"筛选器允许您创建自定义日期范围、而不是仅选择预定义的天数范围。例如、您可以查找"创建时间"为"超过6个月"或"最近10天"内"上次修改"日期的文件。
* 现在、您可以使用"文件路径"筛选器指定要从筛选的查询结果中排除的路径。如果输入包含和排除某些数据的路径、则Data sense会首先查找包含的路径中的所有文件、然后从排除的路径中删除文件、并显示结果。


https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["查看可用于调查数据的所有筛选器的列表"]。



=== 数据感知可以标识日语个人编号

数据感知功能可以识别包含日语个人编号(也称为"我的编号")的文件并对其进行分类。这包括"个人"和"公司我的号码"。 https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-personal-data["查看 Data sense 可以在您的数据中识别的所有类型的个人数据"]。



== 2022年12月11日(1.18版)



=== 内部安装增强功能

内部Data sense安装增加了以下增强功能：

* 现在、在内部主机上开始安装之前、系统会检查一些其他前提条件。这有助于确保主机系统已完全准备好安装Data sense软件：
+
** 测试上是否有足够的空间 `/var/lib/docker`， `/tmp`，和 `/opt`
** 测试所有所需文件夹上的相关权限


* 现在、在配置页面中、工作环境部分将显示_Working Environment ID_和_扫描 程序组_名称。如果您计划使用多个Data sense主机来提供额外的处理能力来扫描数据源、则需要了解工作环境ID。
* 此外、在配置页面中、还会显示一个新部分、其中显示了您设置的扫描程序组以及每个组中的扫描程序节点。


https://docs.netapp.com/us-en/cloud-manager-data-sense/task-deploy-compliance-onprem.html["了解有关在一台主机服务器和多台主机上安装Data sense的更多信息"]。



== 2022年11月13日(1.17版)



=== 支持扫描SharePoint内部部署帐户

Data sense现在可以同时扫描SharePoint Online帐户和SharePoint内部部署帐户(SharePoint Server)。如果您需要在自己的服务器上或无法访问Internet的站点上安装SharePoint、现在可以让Data sense扫描这些帐户中的用户文件。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-scanning-sharepoint.html#adding-a-sharepoint-on-premise-account["了解更多信息。"^]。



=== 能够重新扫描多个目录(文件夹或共享)

现在、您可以立即重新扫描多个目录(文件夹或共享)、以便在系统中反映所做的更改。这样、您可以优先重新扫描某些数据、而不是重新扫描其他数据。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["请参见如何重新扫描目录"^]。



=== 可以添加其他内部"扫描程序"节点来扫描特定数据源

如果您在内部位置安装了Data sense、并且发现扫描某些数据源需要更多的扫描处理能力、则可以添加更多的"扫描程序"节点并将其分配给扫描这些数据源。您可以在安装管理器节点后立即添加扫描程序节点、也可以稍后添加扫描程序节点。

如有必要、可以将扫描程序节点安装在物理上更接近要扫描的数据源的主机系统上。扫描程序节点与数据的距离越近、越好、因为它可以在扫描数据时尽可能地减少网络延迟。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-deploy-compliance-onprem.html#add-scanner-nodes-to-an-existing-deployment["请参见如何安装扫描程序节点以扫描其他数据源"^]。



=== 现在、内部安装程序会在开始安装之前执行预检查

在Linux系统上安装Data sense时、安装程序会在开始实际安装之前检查系统是否满足所有必要的要求(CPU、RAM、容量、网络等)。这有助于在*之前*花费时间进行安装时发现问题。



== 2022年9月6日(1.16版)



=== 能够立即重新扫描存储库以反映文件中的更改

如果您需要立即重新扫描特定存储库以使更改反映在系统中、则可以选择该存储库并重新扫描它。这样、您可以优先重新扫描某些数据、而不是重新扫描其他数据。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["请参见如何重新扫描目录"^]。



=== 在"数据调查"页面中为数据感知扫描状态添加了新的筛选器

使用"分析状态"筛选器可以列出处于数据感知扫描特定阶段的文件。您可以选择一个选项来显示要扫描的*正在等待首次扫描*、正在扫描的*已完成*、*正在等待重新扫描*或*已失败*文件的列表。

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["查看可用于调查数据的所有筛选器的列表"^]。



=== 现在、数据主体被视为扫描中"个人数据"的一部分

Data sense现在可将数据主题视为合规性信息板中显示的个人结果的一部分。此外、在"调查"页面中执行搜索时、您可以选择"个人数据"下的"数据主体"、以便仅查看包含数据主体的文件。



=== 现在、数据感知痕迹文件被视为扫描中"类别"的一部分

Data sense现在可将痕迹文件识别为合规性信息板中显示的类别的一部分。这些文件是Data sense在将文件从源位置移动到NFS共享时创建的。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["详细了解如何创建痕迹文件"^]。

此外、在"调查"页面中执行搜索时、您可以选择"类别"下的"数据感知痕迹"、以便仅查看数据感知痕迹文件。



== 2022年8月7日(1.15版)



=== Data sense可识别来自新西兰的五种新类型的个人数据

Data sense可以识别包含以下类型数据的文件并对其进行分类：

* 新西兰银行帐号
* 新西兰驾驶执照编号
* 新西兰IRD编号(税务ID)
* 新西兰NHI (国家健康指数)编号
* 新西兰的护照编号


link:reference-private-data-categories.html#types-of-personal-data["查看 Data sense 可以在您的数据中识别的所有类型的个人数据"]。



=== 能够添加痕迹文件以指示文件移动的原因

使用数据感知功能将源文件移动到NFS共享时、现在可以将痕迹文件保留在移动文件的位置。痕迹文件可帮助用户了解文件从其原始位置移动的原因。对于每个移动的文件、系统会在源位置`<filename>-breadcrumb-<date>.txt`创建一个痕迹文件、以显示文件移动位置以及文件移动用户。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["了解更多信息。"^]。



=== 在您的目录中找到的个人数据和敏感的个人数据显示在调查结果中

现在、"数据调查"页面将显示在您的目录(文件夹和共享)中找到的个人数据和敏感个人数据的结果。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#viewing-files-that-contain-personal-data["请参见此处的示例"^]。



=== 查看已成功分类的卷、分段等数量的状态

查看Data sense正在扫描的各个存储库(卷、存储分段等)时、现在您可以查看已"映射"的存储库数量以及已"分类"的存储库数量。由于正在对所有数据执行完整的AI标识、因此分类所需时间更长。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#viewing-the-scan-status-for-your-repositories["请参见如何查看此信息"^]。



=== 现在、您可以添加Data sense在数据中标识的自定义模式

您可以通过两种方式添加自定义"个人数据"、Data sense将在未来扫描中识别这些数据。这样、您就可以全面了解潜在敏感数据在所有组织文件中的位置。

* 您可以从文本文件添加自定义关键字。
* 您可以使用正则表达式(regex)添加个人模式。


这些关键字和模式将添加到Data sense已使用的现有预定义模式中、其结果将显示在"Personal Patterns"部分下。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html["了解更多信息。"^]。



== 2022年7月6日(1.14版)



=== 现在、您可以查看有权访问目录的用户和组

过去、您可以查看为单个文件授予的打开权限类型。现在、您可以查看有权访问目录(文件夹和文件共享)的所有用户或组的列表及其权限类型。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#viewing-permissions-for-files-and-directories["了解如何查看有权访问文件夹和文件共享的用户和组"]。



=== 您可以"暂停"扫描存储库、以暂时停止扫描某些内容

暂停扫描意味着Data sense不会对卷或存储分段的任何添加或更改执行未来扫描、但系统中仍会显示所有当前结果。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#pausing-and-resuming-scanning-for-a-repository["请参见如何暂停和恢复扫描"]。



=== Data sense可识别来自另外三种状态的美国驾驶证数据

Data sense可以识别和分类包含来自印第安纳、纽约和德克萨斯州的驾驶执照数据的文件。 link:reference-private-data-categories.html#types-of-personal-data["查看 Data sense 可以在您的数据中识别的所有类型的个人数据"]。



=== 现在、策略将返回与搜索条件匹配的目录

过去、在创建自定义策略时、结果会显示与搜索条件匹配的文件。现在、结果还会显示与查询匹配的目录(文件夹和文件共享)。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-org-private-data.html#creating-custom-policies["了解有关创建策略的更多信息"]。



=== 目前、数据感知一次最多可移动100、000个文件

如果您计划使用Data sense将文件从扫描的数据源移动到NFS共享、则最大文件数已增加到100、000个。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["请参见如何使用Data sense移动文件"]。



== 2022年6月12日(1.13.1版)



=== 现在、您可以从数据调查页面下载结果、并将其作为.json报告

在"数据调查"页面中筛选数据后、除了将数据保存到本地系统上的.CSV文件之外、您还可以将数据另存为可导出到NFS共享的.JSON文件中的报告。确保Data sense具有正确的导出访问权限。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-generating-compliance-reports.html#data-investigation-report["请参见如何从"数据调查"页面创建报告"]。



=== 可以从Data sense UI卸载Data sense

您可以卸载Data sense以从主机中永久删除软件、如果部署了云、则删除部署了Data sense的虚拟机/实例。删除此实例将永久删除Data sense已扫描的所有索引信息。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-uninstall-data-sense.html["了解如何操作"]。



=== 现在、可以使用审核日志记录来跟踪Data sense已执行操作的历史记录

审核日志可跟踪Data sense对所有工作环境中的文件以及Data sense正在扫描的数据源执行的管理活动。活动可以是由用户生成的(删除文件、创建策略等)、也可以是由策略生成的(自动向文件添加标签、自动删除文件等)。

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-audit-data-sense-actions.html["查看有关审核日志的更多详细信息"]。



=== 新的筛选器用于在"数据调查"页面中输入敏感标识符的数量

通过"标识符数量"筛选器、您可以列出具有一定数量的敏感标识符的文件、包括个人数据和敏感个人数据。您可以选择1-10或501到1000等范围、以便仅查看包含该数量的敏感标识符的文件。

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["查看可用于调查数据的所有筛选器的列表"]。



=== 现在、您可以编辑已创建的现有策略

如果您需要更改过去创建的自定义策略、现在可以编辑该策略、而不是创建新策略。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-org-private-data.html#editing-policies["请参见如何编辑策略"]。



== 2022年5月11日(1.12.1版)



=== 增加了对扫描Google Drive帐户中数据的支持

现在、您可以将Google Drive帐户添加到Data sense中、以便扫描这些Google Drive帐户中的文档和文件。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-scanning-google-drive.html["了解如何扫描Google Drive帐户"]。

除了文档、工作表和幻灯片之外、Data sense还可以识别以下Google文件类型中的个人身份信息(Personal Identifiable Information、PiII) https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-files["现有文件类型"]。



=== 已将目录级别视图添加到数据调查页面

除了查看和筛选所有文件和数据库中的数据之外、现在您还可以在"数据调查"页面中根据文件夹和共享中的所有数据查看和筛选数据。将为扫描的CIFS和NFS共享以及OneDrive、SharePoint和Google Drive文件夹的目录编制索引。现在、您可以在目录级别查看权限并管理数据。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["了解如何为扫描的数据选择目录视图"]。



=== 展开组以显示有权访问文件的用户/成员

现在、您可以在Data sense权限功能中查看有权访问文件的用户和组列表。可以展开每个组以显示组中的用户列表。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#viewing-permissions-for-files["了解如何查看对文件具有读取和/或写入权限的用户和组"]。



=== 数据调查页面添加了两个新的筛选器

* 通过"目录类型"筛选器、您可以细化数据以仅查看文件夹或共享。结果将显示在新的*目录*选项卡中。
* 通过"用户/组权限"筛选器、您可以列出特定用户或组具有读取和/或写入权限的文件、文件夹和共享。您可以选择多个用户和/或组名称-或输入部分名称。


https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["查看可用于调查数据的所有筛选器的列表"]。



== 2022年4月5日(1.11.1版)



=== Data sense 可以识别四种新类型的澳大利亚个人数据

Data sense可以识别包含澳大利亚TFN (税务文件编号)、澳大利亚驾驶执照编号、澳大利亚医疗保健服务编号和澳大利亚护照编号的文件并对其进行分类。 link:reference-private-data-categories.html#types-of-personal-data["查看 Data sense 可以在您的数据中识别的所有类型的个人数据"]。



=== 现在，全局 Active Directory 服务器可以是 LDAP 服务器

与 Data sense 集成的全局 Active Directory 服务器现在可以是 LDAP 服务器，而不是以前支持的 DNS 服务器。 link:task-add-active-directory-datasense.html["有关详细信息，请访问此处"]。



== 2022年3月15日(1.10.0版)



=== 新筛选器可显示特定用户或组具有读取或写入权限的文件

添加了一个名为 " 用户 / 组权限 " 的新筛选器，您可以列出特定用户或组具有读取和 / 或写入权限的文件。您可以选择一个或多个用户和/或组名称-或输入部分名称。此功能适用于 Cloud Volumes ONTAP ，内部 ONTAP ， Azure NetApp Files ，适用于 ONTAP 的 Amazon FSx 和文件共享上的卷。



=== Data sense 可以确定 SharePoint 和 OneDrive 帐户中文件的权限

Data sense 现在可以读取 OneDrive 帐户和 SharePoint 帐户中正在扫描的文件的权限。此信息显示在 " 调查 " 窗格中的文件详细信息以及 " 监管信息板 " 中的 " 打开权限 " 区域中。



=== Data sense 还可以识别另外两种类型的个人数据

* 法语 INSEE — INSEE 代码是法国国家统计和经济研究所（ INSEE ）用来标识各种实体的数字代码。
* 密码—此信息通过查找字母数字字符串旁边的 "password" 一词的组合来使用接近验证来标识。找到的项目数将在合规性信息板的 " 个人结果 " 下列出。您可以使用筛选器 * 个人数据 > 密码 * 在调查窗格中搜索包含密码的文件。




=== 支持在非公开站点中部署时扫描 OneDrive 和 SharePoint 数据

如果您已在无法访问Internet的内部站点中的主机上部署Cloud Data sense、则现在可以扫描OneDrive帐户或SharePoint帐户中的本地数据。 link:task-deploy-compliance-dark-site.html#sharepoint-and-onedrive-special-requirements["您需要允许访问以下端点。"]



=== 此版本已停止使用 Cloud Data sense 扫描 Cloud Backup 文件的测试版功能



== 2022 年 2 月 9 日



=== 增加了对扫描 Microsoft SharePoint 联机帐户的支持

现在，您可以将 SharePoint 联机帐户添加到 Data sense 中，以便扫描 SharePoint 站点中的文档和文件。 link:task-scanning-sharepoint.html["了解如何扫描 SharePoint 帐户"]。



=== Data sense 可以将文件从数据源复制到目标位置，并同步这些文件

如果您要迁移数据，并且希望捕获最近对文件所做的任何更改，则此功能非常有用。此操作将使用 https://docs.netapp.com/us-en/cloud-manager-sync/concept-cloud-sync.html["NetApp Cloud Sync"^] 用于将数据从源复制并同步到目标的功能。

link:task-managing-highlights.html#copying-and-synchronizing-source-files-to-a-target-system["请参见如何复制和同步文件"]。



=== 为 DAR 报告提供了新的语言支持

现在，在搜索数据主体名称以创建数据主体访问请求（ Data Subject Access Request ， DSAar ）报告时，支持德语和西班牙语。本报告旨在帮助贵组织满足 GDPR 或类似数据隐私法律的要求。



=== Data sense 可识别另外三种类型的个人数据

Data sense 现在可以在文件中找到法语社会安全号码，法语 ID 和法语驱动程序许可证号码。 link:reference-private-data-categories.html#types-of-personal-data["查看 Data sense 在扫描中标识的所有个人数据类型的列表"]。



=== 已更改安全组端口，以便与连接器进行数据感知通信

Cloud Manager Connector 的安全组将使用端口 443 而非端口 80 来处理传入和传出 Data sense 实例的入站和出站流量，以提高安全性。此时，这两个端口都保持打开状态，因此您不应看到任何问题，但您应在任何早期的 Connector 部署中更新安全组，因为端口 80 将在未来版本中弃用。



== 2022 年 1 月 2 日



=== 能够集成全局 Active Directory 以确定文件所有者和权限

现在，您可以将全局 Active Directory 与 Cloud Data sense 集成在一起，以增强 Data sense 报告的有关文件所有者以及哪些用户和组有权访问您的文件的结果。

除了您输入 Active Directory 凭据以使 Data sense 能够从某些数据源扫描 CIFS 卷之外，此新集成还为其他用户和系统提供了额外的集成。Data sense 将在所有集成的 Active Directory 中查找用户和权限详细信息。 link:task-add-active-directory-datasense.html["请参见如何设置全局 Active Directory"]。



=== 现在，可以使用数据感知 " 策略 " 删除文件

Data sense 可以自动删除与策略中定义的查询匹配的文件。 link:task-managing-highlights.html#deleting-source-files-automatically-using-policies["请参见如何创建自定义策略"]。



== 2021 年 12 月 16 日



=== 数据感知功能可以扫描非公开站点中的数据

Cloud Manager （ Connector ）和 Cloud Data sense 均可部署在无法访问 Internet 的内部站点中。现在，您的安全站点可以使用 Cloud Manager 管理内部 ONTAP 集群，在集群之间复制数据，以及使用 Cloud Data sense 扫描这些集群中的数据。

link:task-deploy-compliance-dark-site.html["了解如何在无法访问 Internet 的站点中部署 Cloud Data sense"^]。



== 2021 年 11 月 28 日



=== 数据感知可用于从 ONTAP 系统克隆卷

您可以使用 Data sense 克隆 ONTAP 卷，但在新克隆的卷中只包含源卷中的选定文件。如果您要迁移数据并希望排除某些文件，或者要创建卷的副本以供测试，则此功能非常有用。

link:task-managing-highlights.html#cloning-volume-data-to-a-new-volume["请参见如何克隆卷"]。



=== 现在， Cloud Manager 的 GCP Marketplace 订阅支持 Cloud Data sense

。 https://console.cloud.google.com/marketplace/details/netapp-cloudmanager/cloud-manager?supportedpurview=project&rif_reserved["Cloud Manager 的 GCP Marketplace 订阅"^] 现在支持 Cloud Data sense 。现在，除了使用 NetApp 的 BYOL 许可证之外，您还可以使用此按需购买（ PAYGO ）订阅从部署在 Google Cloud 存储上的 Cloud Volumes ONTAP 系统扫描数据。



=== 能够查看长期运行的合规性操作的状态

从调查结果窗格对多个文件运行操作时，例如删除 50 个文件，此过程可能需要一些时间。现在，您可以监控这些异步操作的状态，以便了解它何时应用于所有文件。

link:task-view-compliance-actions.html["了解如何查看持续合规操作的状态"]。



=== Data sense 还可以识别另外两种类型的个人数据

Data sense 现在可以在文件中找到个人数据类型 " 英国护照 " 和 " 国家卫生服务（ NHS ）编号 " 。 link:reference-private-data-categories.html#types-of-personal-data["查看 Data sense 在扫描中发现的所有个人数据类型的列表"]。



=== 新的筛选器可显示属于特定工作环境类型的文件

在 " 数据调查 " 页面中筛选数据时，为 " 工作环境类型 " 添加了一个新的筛选器。这样，您可以筛选 Cloud Volumes ONTAP 系统，适用于 ONTAP 系统的 FSX ，内部 ONTAP 系统等的结果。



== 2021 年 11 月 7 日



=== 现在，您可以选择对工作环境中的各个卷进行映射或分类

过去，您可以映射所有卷，也可以映射并分类每个工作环境中的所有卷。现在，您可以选择映射 _or_ 映射各个卷并对其进行分类。此选项适用于 Cloud Volumes ONTAP 卷， ANF 卷，内部 ONTAP 卷以及 ONTAP 卷的 FSX 。



=== 数据感知可以将文件从数据源复制到目标 NFS 共享

您可以将 Data sense 正在扫描的任何源文件复制到目标 NFS 共享。如果要为某些数据创建副本并将其移动到其他 NFS 位置，此功能将非常有用。 link:task-managing-highlights.html#copying-source-files-to-an-nfs-share["了解更多信息。"]。



=== 可以扫描 ONTAP 文件系统的 FSX 上的数据保护卷

现在，您可以在 ONTAP 文件系统的 FSX 上扫描数据保护卷。 link:task-scanning-fsx.html#scanning-data-protection-volumes["了解更多信息。"]。



=== 新的筛选器可按 Data sense 首次发现文件时的日期范围显示文件

通过 " 调查 " 页面中的一个名为 " 发现时间 " 的新筛选器，您可以按 Data sense 首次发现文件时的日期范围查看文件。发现的时间也已添加到 " 文件详细信息 " 页面以及以 CSV 格式为文件输出的报告中。



=== SOC 2 类型 2 认证

一家独立的认证公有 会计师事务所和服务审计师对云数据感知进行了检查，并确认它已根据适用的信任服务标准获得 SOC 2 类型 2 报告。

https://www.netapp.com/company/trust-center/compliance/soc-2/["查看 NetApp 的 SOC 2 报告"^]。



== 2021 年 10 月 4 日



=== 支持 NetApp 的 BYOL 许可

除了通过云提供商市场许可 Data sense 之外，现在您还可以从 NetApp 购买自带许可证（ BYOL ），该许可证可用于所有工作环境和 Cloud Manager 帐户中的数据源。

link:task-licensing-datasense.html#use-a-cloud-data-sense-byol-license["了解有关全新 Cloud Data sense BYOL 许可证的更多信息"]。



=== 支持 Google Cloud Platform

现在， Cloud Data sense 可以扫描部署在 GCP 上的 Cloud Volumes ONTAP 系统中的数据。数据感知必须部署在 GCP 上，而连接器必须部署在 GCP 或内部环境中。与 Connector 关联的 GCP 服务帐户需要最新权限才能将 Cloud Data sense 部署到 GCP 。



=== 可以在 ONTAP 文件系统的 FSX 上扫描 CIFS 卷

现在， Data sense 可以从 ONTAP 系统的 FSX 扫描 CIFS 卷。 link:task-scanning-fsx.html["请参见如何扫描 Amazon FSX 中的 ONTAP 卷"]。



== 2021 年 9 月 2 日



=== 可以在 ONTAP 文件系统的 FSX 上扫描 NFS 卷

增加了对在适用于 ONTAP 系统的 Amazon FSX 上扫描 NFS 卷上数据的支持。 link:task-scanning-fsx.html["请参见如何为适用于 ONTAP 的 FSX 系统配置扫描"]。



=== 数据感知 " 状态 " 条目已更改为 " 标记 " 条目

使用 Data sense 向文件添加 " 状态 " 信息的功能已将术语更改为 " 标记 " 。这些标记是文件级标记，请勿与可应用于卷， EC2 实例，虚拟机等的资源级标记相混淆 link:task-org-private-data.html#applying-tags-to-manage-your-scanned-files["了解有关文件级标记的更多信息"]。



== 2021 年 8 月 1 日



=== 一次可管理多个文件的文件设置

在早期版本的 Cloud Data sense 中，您可以一次对一个文件执行以下操作：添加状态标记，分配用户和添加 AIP 标签。现在，您可以从 " 数据调查 " 页面中选择多个文件，并对多个文件执行其中每个操作。



=== " 监管 " 信息板可显示数据的创建时间或上次访问时间

在 " 监管 " 信息板中查看 " 数据期限 " 图时，除了根据上次修改时间查看数据之外，现在您还可以按数据创建时间或上次访问时间（读取时）查看数据。此信息也会在数据映射报告中提供。



=== 扫描大型配置时，可以使用多个主机提高处理能力

在内部部署 Data sense 时，如果您计划扫描包含 PB 数据的配置，现在可以在其他内部主机上安装扫描软件。在扫描非常大的配置时，这些额外的 _scanner nodes_ 可提高处理能力。

请参见操作说明 link:task-deploy-compliance-onprem.html#multi-host-installation-for-large-configurations["在多个主机上部署 Data sense 软件"]。



== 2021 年 7 月 7 日



=== 数据感知可以将文件从数据源移动到目标 NFS 共享

通过一项新功能，您可以实现 link:task-managing-highlights.html#moving-source-files-to-an-nfs-share["将 Data sense 正在扫描的任何源文件移动到任何 NFS 共享"]。这样，您可以将敏感或与安全相关的文件移动到特定区域，以便进行更多分析。



=== 能够快速对数据进行分类，而不是执行完整的分类扫描

现在，您可以选择快速将数据映射到类别中，而不是执行完整的分类扫描。这样，您就可以了 link:task-generating-compliance-reports.html#data-mapping-report["查看数据映射报告"] 从 " 监管信息板 " 中查看您的数据概览，了解您不需要对某些数据源运行完整扫描的情况。



=== 能够将文件分配给 Cloud Manager 用户

现在可以了 link:task-org-private-data.html#assigning-users-to-manage-certain-files["将文件分配给特定 Cloud Manager 用户"] 这样，该人员就可以负责对文件执行任何后续操作。此功能可与现有功能结合使用，以便向文件添加自定义标记。

通过 " 调查 " 页面中的新筛选器，您还可以轻松查看 " 已分配给 " 字段中具有相同人员的所有文件。



=== 能够使用较小的 Cloud Data sense 实例

一些扫描要求较低的用户要求能够使用较小的 Cloud Data sense 实例。现在可以了。因此，使用这些较小实例时存在一些限制 link:concept-cloud-compliance.html#using-a-smaller-instance-type["请先了解这些限制"]。



=== 能够执行慢速扫描

数据扫描对存储系统和数据的影响可以忽略不计。但是，如果您担心即使影响很小，也可以将 Data sense 配置为立即执行 " 缓慢 " 扫描。 link:task-reduce-scan-speed.html["了解如何操作"]。



=== 数据感知可跟踪上次访问文件的时间

上次访问时间值已添加到 " 文件详细信息 " 页面以及以 CSV 格式输出的报告中，以便您可以查看用户上次访问文件的时间。
