---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense' 
summary: 了解BlueXP分类中的新增功能。 
---
= BlueXP的新增功能分类
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解BlueXP分类中的新增功能。



== 2023年6月6日(版本1.23)



=== 现在、搜索数据主题名称时支持日语

现在、在响应数据主体访问请求(Data Subject Access Request、DSAR)搜索主体名称时、可以输入日语名称。您可以生成 https://docs.netapp.com/us-en/bluexp-classification/task-generating-compliance-reports.html#what-is-a-data-subject-access-request["数据主体访问请求报告"] 以及生成的信息。您也可以在中输入日语名称 https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#filter-data-by-sensitivity-and-content[""数据调查"页面中的"数据主题"筛选器"] 标识包含主题名称的文件。



=== Ubuntu现在是一个受支持的Linux分发版、您可以在其中安装BlueXP分类

Ubuntu 22.04已被认定为BlueXP分类支持的操作系统。您可以在网络中的Ubuntu Linux主机或云中的Linux主机上安装BlueXP分类。 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["了解如何在安装了Ubuntu的主机上安装BlueXP分类"]。



=== 新的BlueXP分类安装不再支持Red Hat Enterprise Linux 8.6和8.7

新部署不支持这些版本、因为Red Hat不再支持Docker、而Docker是前提条件。如果现有BlueXP分类计算机运行RHEL 8.6或8.7、则NetApp将继续支持您的配置。



=== 可以将BlueXP分类配置为FPolicy收集器、以便从ONTAP系统接收FPolicy事件

您可以在BlueXP分类系统上为工作环境中的卷上检测到的文件访问事件收集文件访问审核日志。BlueXP分类可以捕获以下类型的FPolicy事件以及对文件执行操作的用户：创建、读取、写入、删除、重命名、 Change owner/permissions和Change SACL/DACL。 https://docs.netapp.com/us-en/bluexp-classification/task-manage-file-access-events.html["请参见如何监控和管理文件访问事件"]。



=== 现在、非公开站点支持Data sense BYOL许可证

现在、您可以将Data Sense BYOL许可证上传到非公开站点的BlueXP数字钱包中、以便在许可证不足时收到通知。 https://docs.netapp.com/us-en/bluexp-classification/task-licensing-datasense.html#obtain-your-bluexp-classification-license-file["了解如何获取和上传Data sense BYOL许可证"]。



== 2023年4月3日(1.22版)



=== 新的数据发现评估报告

数据发现评估报告对扫描环境进行了深入分析、以突出显示系统的发现结果、并显示关注领域和可能的修复步骤。本报告的目标是提高对数据治理问题、数据安全风险以及数据集数据合规性差距的认识。 https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html#data-discovery-assessment-report["请参见如何生成和使用数据发现评估报告"]。



=== 能够在云中的较小实例上部署BlueXP分类

在AWS环境中从BlueXP Connector部署BlueXP分类时、现在您可以从两种比默认实例更小的实例类型中进行选择。如果您要扫描小型环境、这可以帮助您节省云成本。但是、使用较小的实例时会存在一些限制。 https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html#using-a-smaller-instance-type["请参见可用的实例类型和限制"]。



=== 现在、可以使用独立脚本在安装BlueXP分类之前对Linux系统进行资格认定

如果要独立于运行BlueXP分类安装来验证Linux系统是否满足所有前提条件、您可以下载一个单独的脚本、该脚本仅测试前提条件。 https://docs.netapp.com/us-en/bluexp-classification/task-test-linux-system.html["请参见How to check if your Linux host is ready to install BlueXP classification"]。



== 2023年3月7日(1.21版)



=== 新增了一项功能、可从BlueXP分类UI添加您自己的自定义类别

现在、您可以通过BlueXP分类添加自己的自定义类别、以便BlueXP分类能够识别适合这些类别的文件。BlueXP分类有很多 https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-categories["预定义的类别"]、因此、您可以通过此功能添加自定义类别、以确定您的组织独有的信息在您的数据中的位置。

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-categories["了解更多信息。"^]。



=== 现在、您可以从BlueXP分类UI添加自定义关键字

BlueXP分类可以添加BlueXP分类在未来扫描中识别的自定义关键字。但是、您需要登录到BlueXP classification Linux主机并使用命令行界面添加关键字。在此版本中、BlueXP分类UI中提供了添加自定义关键字的功能、因此可以轻松添加和编辑这些关键字。

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-keywords-from-a-list-of-words["了解有关从BlueXP分类UI添加自定义关键字的更多信息"^]。



=== 当"上次访问时间"将被更改时、BlueXP分类*不*扫描文件的功能

默认情况下、如果BlueXP分类没有足够的"写入"权限、则系统不会扫描卷中的文件、因为BlueXP分类无法将"上次访问时间"还原为原始时间戳。但是、如果您不在乎文件中的上次访问时间是否重置为原始时间、则可以在配置页面中覆盖此行为、以便BlueXP分类将扫描卷、而不管权限如何。

与此功能结合使用时、添加了名为"扫描分析事件"的新筛选器、因此您可以查看因BlueXP分类无法还原上次访问时间而未进行分类的文件、或者即使BlueXP分类无法还原上次访问时间也进行分类的文件。

https://docs.netapp.com/us-en/bluexp-classification/reference-collected-metadata.html#last-access-time-timestamp["了解有关"上次访问时间时间戳"和BlueXP分类所需权限的更多信息"]。



=== BlueXP分类标识了三种新类型的个人数据

BlueXP分类可以标识包含以下类型数据的文件并对其进行分类：

* 博茨瓦纳身份卡(Omang)编号
* 博茨瓦纳的护照编号
* 新加坡国家注册身份卡(NRIC)


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["查看BlueXP分类可在您的数据中识别的所有个人数据类型"]。



=== 更新了目录的功能

* 现在、数据调查报告的"轻型CSV报告"选项包括目录中的信息。
* "上次访问"时间筛选器现在可显示文件和目录的上次访问时间。




=== 安装增强功能

* 现在、不能访问Internet的站点(非公开站点)的BlueXP分类安装程序会执行预检查、以确保您的系统和网络要求已满足、以便成功安装。
* 安装审核日志文件现已保存；它们将写入 `/ops/netapp/install_logs`。




== 2023年2月5日(版本1.20)



=== 能够将基于策略的通知电子邮件发送到任何电子邮件地址

在早期版本的BlueXP分类中、当某些关键策略返回结果时、您可以向帐户中的BlueXP用户发送电子邮件警报。通过此功能、您可以在未联机时收到通知以保护数据。现在、您还可以将策略中的电子邮件警报发送给不在您的BlueXP帐户中的任何其他用户、最多20个电子邮件地址。

https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html#sending-email-alerts-when-non-compliant-data-is-found["了解有关根据策略结果发送电子邮件警报的更多信息"]。



=== 现在、您可以从BlueXP分类UI添加个人模式

BlueXP分类可以添加BlueXP分类在未来一段时间内将识别的自定义"个人数据"。但是、您需要登录到BlueXP classification Linux主机并使用命令行添加自定义模式。在此版本中、BlueXP分类UI中提供了使用正则表达式添加个人模式的功能、因此可以轻松添加和编辑这些自定义模式。

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-personal-data-identifiers-using-a-regex["从BlueXP分类UI中了解有关添加自定义模式的更多信息"^]。



=== 能够使用BlueXP分类移动1、500万个文件

过去、您可以让BlueXP分类将最多100、000个源文件移动到任何NFS共享。现在、一次最多可以移动1500万个文件。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html#moving-source-files-to-an-nfs-share["了解有关使用BlueXP分类移动源文件的更多信息"]。



=== 能够查看有权访问SharePoint Online文件的用户数量

筛选器"可访问的用户数"现在支持存储在SharePoint Online存储库中的文件。过去仅支持CIFS共享上的文件。请注意、目前不会在此筛选器中计入非基于Active Directory的SharePoint组。



=== 已将新的"部分成功"状态添加到"操作状态"面板中

新的"部分成功"状态表示BlueXP分类操作已完成、某些项目失败、而某些项目成功、例如、当您移动或删除100个文件时。此外、"已完成"状态已重命名为"成功"。过去、"已完成"状态可能会列出成功和失败的操作。现在、"成功"状态意味着对所有项目执行的所有操作都成功。 https://docs.netapp.com/us-en/bluexp-classification/task-view-compliance-actions.html["请参见如何查看操作状态面板"]。



== 2023年1月9日(1.19版)



=== 可以查看包含敏感数据且过于宽松的文件图表

"监管"信息板添加了一个新的"敏感数据和宽权限"区域、用于为包含敏感数据(包括敏感和敏感个人数据)且过于宽松的文件提供热图。这样可以帮助您了解敏感数据可能存在哪些风险。 https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html#data-listed-by-sensitivity-and-wide-permissions["了解更多信息。"]。



=== 数据调查页面提供了三个新筛选器

可以使用新筛选器细化数据调查页面中显示的结果：

* "Number of users with access"筛选器显示了哪些文件和文件夹对一定数量的用户开放。您可以选择一个数字范围来细化结果、例如、查看51-100个用户可访问哪些文件。
* 现在、"创建时间"、"发现时间"、"上次修改时间"和"上次访问时间"筛选器允许您创建自定义日期范围、而不是仅选择预定义的天数范围。例如、您可以查找"创建时间"为"超过6个月"或"最近10天"内"上次修改"日期的文件。
* 现在、您可以使用"文件路径"筛选器指定要从筛选的查询结果中排除的路径。如果您输入包含和排除某些数据的路径、BlueXP分类会首先查找包含路径中的所有文件、然后从排除的路径中删除文件、最后显示结果。


https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#filtering-data-in-the-data-investigation-page["查看可用于调查数据的所有筛选器的列表"]。



=== BlueXP分类可以标识日语个人编号

BlueXP分类可以识别包含日语个人编号(也称为"我的编号")的文件并对其进行分类。这包括"个人"和"公司我的号码"。 https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["查看BlueXP分类可在您的数据中识别的所有个人数据类型"]。



== 2022年12月11日(1.18版)



=== 内部安装增强功能

内部Data sense安装增加了以下增强功能：

* 现在、在内部主机上开始安装之前、系统会检查一些其他前提条件。这有助于确保主机系统已完全准备好安装Data sense软件：
+
** 测试上是否有足够的空间 `/var/lib/docker`， `/tmp`，和 `/opt`
** 测试所有所需文件夹上的相关权限


* 现在、在配置页面中、工作环境部分将显示_Working Environment ID_和_扫描 程序组_名称。如果您计划使用多个Data sense主机来提供额外的处理能力来扫描数据源、则需要了解工作环境ID。
* 此外、在配置页面中、还会显示一个新部分、其中显示了您设置的扫描程序组以及每个组中的扫描程序节点。


https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["了解有关在一台主机服务器和多台主机上安装Data sense的更多信息"]。



== 2022年11月13日(1.17版)



=== 支持扫描SharePoint内部部署帐户

Data sense现在可以同时扫描SharePoint Online帐户和SharePoint内部部署帐户(SharePoint Server)。如果您需要在自己的服务器上或无法访问Internet的站点上安装SharePoint、现在可以让Data sense扫描这些帐户中的用户文件。 https://docs.netapp.com/us-en/bluexp-classification/task-scanning-sharepoint.html#adding-a-sharepoint-on-premise-account["了解更多信息。"^]。



=== 能够重新扫描多个目录(文件夹或共享)

现在、您可以立即重新扫描多个目录(文件夹或共享)、以便在系统中反映所做的更改。这样、您可以优先重新扫描某些数据、而不是重新扫描其他数据。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["请参见如何重新扫描目录"^]。



=== 可以添加其他内部"扫描程序"节点来扫描特定数据源

如果您在内部位置安装了Data sense、并且发现扫描某些数据源需要更多的扫描处理能力、则可以添加更多的"扫描程序"节点并将其分配给扫描这些数据源。您可以在安装管理器节点后立即添加扫描程序节点、也可以稍后添加扫描程序节点。

如有必要、可以将扫描程序节点安装在物理上更接近要扫描的数据源的主机系统上。扫描程序节点与数据的距离越近、越好、因为它可以在扫描数据时尽可能地减少网络延迟。 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html#add-scanner-nodes-to-an-existing-deployment["请参见如何安装扫描程序节点以扫描其他数据源"^]。



=== 现在、内部安装程序会在开始安装之前执行预检查

在Linux系统上安装Data sense时、安装程序会在开始实际安装之前检查系统是否满足所有必要的要求(CPU、RAM、容量、网络等)。这有助于在*之前*花费时间进行安装时发现问题。



== 2022年9月6日(1.16版)



=== 能够立即重新扫描存储库以反映文件中的更改

如果您需要立即重新扫描特定存储库以使更改反映在系统中、则可以选择该存储库并重新扫描它。这样、您可以优先重新扫描某些数据、而不是重新扫描其他数据。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["请参见如何重新扫描目录"^]。



=== 在"数据调查"页面中为数据感知扫描状态添加了新的筛选器

使用"分析状态"筛选器可以列出处于数据感知扫描特定阶段的文件。您可以选择一个选项来显示要扫描的*正在等待首次扫描*、正在扫描的*已完成*、*正在等待重新扫描*或*已失败*文件的列表。

https://docs.netapp.com/us-en/bluexp-classification/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["查看可用于调查数据的所有筛选器的列表"^]。



=== 现在、数据主体被视为扫描中"个人数据"的一部分

Data sense现在可将数据主题视为合规性信息板中显示的个人结果的一部分。此外、在"调查"页面中执行搜索时、您可以选择"个人数据"下的"数据主体"、以便仅查看包含数据主体的文件。



=== 现在、数据感知痕迹文件被视为扫描中"类别"的一部分

Data sense现在可将痕迹文件识别为合规性信息板中显示的类别的一部分。这些文件是Data sense在将文件从源位置移动到NFS共享时创建的。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html#moving-source-files-to-an-nfs-share["详细了解如何创建痕迹文件"^]。

此外、在"调查"页面中执行搜索时、您可以选择"类别"下的"数据感知痕迹"、以便仅查看数据感知痕迹文件。



== 2022年8月7日(1.15版)



=== Data sense可识别来自新西兰的五种新类型的个人数据

Data sense可以识别包含以下类型数据的文件并对其进行分类：

* 新西兰银行帐号
* 新西兰驾驶执照编号
* 新西兰IRD编号(税务ID)
* 新西兰NHI (国家健康指数)编号
* 新西兰的护照编号


link:reference-private-data-categories.html#types-of-personal-data["查看 Data sense 可以在您的数据中识别的所有类型的个人数据"]。



=== 能够添加痕迹文件以指示文件移动的原因

使用数据感知功能将源文件移动到NFS共享时、现在可以将痕迹文件保留在移动文件的位置。痕迹文件可帮助用户了解文件从其原始位置移动的原因。对于移动的每个文件、系统都会在名为的源位置创建一个bed屑 文件 `<filename>-breadcrumb-<date>.txt` 可显示文件的移动位置以及移动文件的用户。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html#moving-source-files-to-an-nfs-share["了解更多信息。"^]。



=== 在您的目录中找到的个人数据和敏感的个人数据显示在调查结果中

现在、"数据调查"页面将显示在您的目录(文件夹和共享)中找到的个人数据和敏感个人数据的结果。 https://docs.netapp.com/us-en/bluexp-classification/task-controlling-private-data.html#viewing-files-that-contain-personal-data["请参见此处的示例"^]。



=== 查看已成功分类的卷、分段等数量的状态

查看Data sense正在扫描的各个存储库(卷、存储分段等)时、现在您可以查看已"映射"的存储库数量以及已"分类"的存储库数量。由于正在对所有数据执行完整的AI标识、因此分类所需时间更长。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#viewing-the-scan-status-for-your-repositories["请参见如何查看此信息"^]。



=== 现在、您可以添加Data sense在数据中标识的自定义模式

您可以通过两种方式添加自定义"个人数据"、Data sense将在未来扫描中识别这些数据。这样、您就可以全面了解潜在敏感数据在所有组织文件中的位置。

* 您可以从文本文件添加自定义关键字。
* 您可以使用正则表达式(regex)添加个人模式。


这些关键字和模式将添加到Data sense已使用的现有预定义模式中、其结果将显示在"Personal Patterns"部分下。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["了解更多信息。"^]。



== 2022年7月6日(1.14版)



=== 现在、您可以查看有权访问目录的用户和组

过去、您可以查看为单个文件授予的打开权限类型。现在、您可以查看有权访问目录(文件夹和文件共享)的所有用户或组的列表及其权限类型。 https://docs.netapp.com/us-en/bluexp-classification/task-controlling-private-data.html#viewing-permissions-for-files-and-directories["了解如何查看有权访问文件夹和文件共享的用户和组"]。



=== 您可以"暂停"扫描存储库、以暂时停止扫描某些内容

暂停扫描意味着Data sense不会对卷或存储分段的任何添加或更改执行未来扫描、但系统中仍会显示所有当前结果。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#pausing-and-resuming-scanning-for-a-repository["请参见如何暂停和恢复扫描"]。



=== Data sense可识别来自另外三种状态的美国驾驶证数据

Data sense可以识别和分类包含来自印第安纳、纽约和德克萨斯州的驾驶执照数据的文件。 link:reference-private-data-categories.html#types-of-personal-data["查看 Data sense 可以在您的数据中识别的所有类型的个人数据"]。



=== 现在、策略将返回与搜索条件匹配的目录

过去、在创建自定义策略时、结果会显示与搜索条件匹配的文件。现在、结果还会显示与查询匹配的目录(文件夹和文件共享)。 https://docs.netapp.com/us-en/bluexp-classification/task-org-private-data.html#creating-custom-policies["了解有关创建策略的更多信息"]。



=== 目前、数据感知一次最多可移动100、000个文件

如果您计划使用Data sense将文件从扫描的数据源移动到NFS共享、则最大文件数已增加到100、000个。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html#moving-source-files-to-an-nfs-share["请参见如何使用Data sense移动文件"]。



== 2022年6月12日(1.13.1版)



=== 现在、您可以从数据调查页面下载结果、并将其作为.json报告

在"数据调查"页面中筛选数据后、除了将数据保存到本地系统上的.CSV文件之外、您还可以将数据另存为可导出到NFS共享的.JSON文件中的报告。确保Data sense具有正确的导出访问权限。 https://docs.netapp.com/us-en/bluexp-classification/task-generating-compliance-reports.html#data-investigation-report["请参见如何从"数据调查"页面创建报告"]。



=== 可以从Data sense UI卸载Data sense

您可以卸载Data sense以从主机中永久删除软件、如果部署了云、则删除部署了Data sense的虚拟机/实例。删除此实例将永久删除Data sense已扫描的所有索引信息。 https://docs.netapp.com/us-en/bluexp-classification/task-uninstall-data-sense.html["了解如何操作"]。



=== 现在、可以使用审核日志记录来跟踪Data sense已执行操作的历史记录

审核日志可跟踪Data sense对所有工作环境中的文件以及Data sense正在扫描的数据源执行的管理活动。活动可以是由用户生成的(删除文件、创建策略等)、也可以是由策略生成的(自动向文件添加标签、自动删除文件等)。

https://docs.netapp.com/us-en/bluexp-classification/task-audit-data-sense-actions.html["查看有关审核日志的更多详细信息"]。



=== 新的筛选器用于在"数据调查"页面中输入敏感标识符的数量

通过"标识符数量"筛选器、您可以列出具有一定数量的敏感标识符的文件、包括个人数据和敏感个人数据。您可以选择1-10或501到1000等范围、以便仅查看包含该数量的敏感标识符的文件。

https://docs.netapp.com/us-en/bluexp-classification/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["查看可用于调查数据的所有筛选器的列表"]。



=== 现在、您可以编辑已创建的现有策略

如果您需要更改过去创建的自定义策略、现在可以编辑该策略、而不是创建新策略。 https://docs.netapp.com/us-en/bluexp-classification/task-org-private-data.html#editing-policies["请参见如何编辑策略"]。



== 2022年5月11日(1.12.1版)



=== 增加了对扫描Google Drive帐户中数据的支持

现在、您可以将Google Drive帐户添加到Data sense中、以便扫描这些Google Drive帐户中的文档和文件。 https://docs.netapp.com/us-en/bluexp-classification/task-scanning-google-drive.html["了解如何扫描Google Drive帐户"]。

除了文档、工作表和幻灯片之外、Data sense还可以识别以下Google文件类型中的个人身份信息(Personal Identifiable Information、PiII) https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-files["现有文件类型"]。



=== 已将目录级别视图添加到数据调查页面

除了查看和筛选所有文件和数据库中的数据之外、现在您还可以在"数据调查"页面中根据文件夹和共享中的所有数据查看和筛选数据。将为扫描的CIFS和NFS共享以及OneDrive、SharePoint和Google Drive文件夹的目录编制索引。现在、您可以在目录级别查看权限并管理数据。 https://docs.netapp.com/us-en/bluexp-classification/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["了解如何为扫描的数据选择目录视图"]。



=== 展开组以显示有权访问文件的用户/成员

现在、您可以在Data sense权限功能中查看有权访问文件的用户和组列表。可以展开每个组以显示组中的用户列表。 https://docs.netapp.com/us-en/bluexp-classification/task-controlling-private-data.html#viewing-permissions-for-files["了解如何查看对文件具有读取和/或写入权限的用户和组"]。



=== 数据调查页面添加了两个新的筛选器

* 通过"目录类型"筛选器、您可以细化数据以仅查看文件夹或共享。结果将显示在新的*目录*选项卡中。
* 通过"用户/组权限"筛选器、您可以列出特定用户或组具有读取和/或写入权限的文件、文件夹和共享。您可以选择多个用户和/或组名称-或输入部分名称。


https://docs.netapp.com/us-en/bluexp-classification/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["查看可用于调查数据的所有筛选器的列表"]。



== 2022年4月5日(1.11.1版)



=== Data sense 可以识别四种新类型的澳大利亚个人数据

Data sense可以识别包含澳大利亚TFN (税务文件编号)、澳大利亚驾驶执照编号、澳大利亚医疗保健服务编号和澳大利亚护照编号的文件并对其进行分类。 link:reference-private-data-categories.html#types-of-personal-data["查看 Data sense 可以在您的数据中识别的所有类型的个人数据"]。



=== 现在，全局 Active Directory 服务器可以是 LDAP 服务器

与 Data sense 集成的全局 Active Directory 服务器现在可以是 LDAP 服务器，而不是以前支持的 DNS 服务器。 link:task-add-active-directory-datasense.html["有关详细信息，请访问此处"]。
