---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense, cloud data sense, bluexp, bluexp classification' 
summary: 了解BlueXP分类中的新增功能。 
---
= BlueXP  分类中的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解BlueXP分类中的新增功能。



== 2025年4月14日



=== 1.42 版

此BlueXP  分类版本包括：

.针对工作环境进行批量扫描
BlueXP  分类现在支持对工作环境执行批量操作。您可以选择启用映射扫描、启用映射和分类扫描、禁用扫描或跨工作环境中的卷创建自定义配置。如果您为单个卷进行选择、则会覆盖批量选择。要执行批量操作，请导航到**配置**页并进行选择。

.在本地下载调查报告
BlueXP  分类现在支持在本地下载数据调查报告以在浏览器中查看。如果您选择本地选项、则数据调查仅以CSV格式提供、并且仅显示前10、000行数据。

有关详细信息，请参见 link:task-investigate-data.html#create-the-data-investigation-report["根据BlueXP  分类调查存储在您的组织中的数据"]。



== 2025年3月10日



=== 1.41 版

此BlueXP  分类版本包括一些常规改进和错误修复。它还包括：

.扫描状态
现在、BlueXP  分类可跟踪卷上_initial-_映射和分类扫描的实时进度。单独的渐进式条可跟踪映射和分类扫描、显示扫描总文件的百分比。您也可以将鼠标悬停在进度条上以查看扫描的文件数和总文件数。跟踪扫描状态可更深入地了解扫描进度、使您能够更好地规划扫描并了解资源分配。

要查看扫描的状态，请导航到BlueXP  分类中的**配置**，然后选择**工作环境配置**。每个卷的进度将以行显示。



== 2025年2月19日



=== 1.40 版

此BlueXP  分类版本包含以下更新。

.支持RHEL 9.5
除了先前支持的版本之外、此版本还支持Red Hat Enterprise Linux v9.5。这适用于BlueXP  分类的任何手动内部安装、包括非公开站点部署。

以下操作系统要求使用Podman容器引擎、并要求使用BlueXP  分类版本1.3或更高版本：Red Hat Enterprise Linux版本8.8、8.10、9.0、9.1、9.2、9.3、9.4和9.5。

.确定仅映射扫描的优先级
执行仅映射扫描时、您可以确定最重要扫描的优先级。如果您有许多工作环境、并希望确保首先完成高优先级扫描、则此功能会很有帮助。

默认情况下、扫描会根据启动顺序进行排队。现在、您可以将扫描移动到队列的前面、从而确定扫描的优先级。可以确定多个扫描的优先级。优先级按先入先出的顺序指定、这意味着您优先处理的第一个扫描将移至队列的前端；您优先处理的第二个扫描将成为队列中的第二个扫描、依此类推。

优先权是一次性授予的。按默认顺序自动重新选择映射数据。

优先级限制为link:concept-cloud-compliance.html["仅映射扫描"]；它不适用于地图扫描和分类扫描。

有关详细信息，请参见 link:task-managing-repo-scanning.html#prioritize-scans["确定扫描优先级"]。

.重试所有扫描
BlueXP  分类现在支持批量重试所有失败的扫描。

现在可以使用**重试全部**功能在批处理操作中重新尝试扫描。如果分类扫描因网络中断等临时问题而失败、您可以使用一个按钮同时重试所有扫描、而不是逐个重试。可以根据需要多次重试扫描。

重试所有扫描：

. 从BlueXP  分类菜单中，选择*Configuration*。
. 要重试所有失败的扫描，请选择*重试所有扫描*。


.提高了分类模型的准确性
的机器学习模型准确性link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["预定义的类别"]提高了11%。



== 2025年1月22日



=== 1.39 版

此BlueXP  分类版本更新了数据调查报告的导出流程。此导出更新适用于对数据执行其他分析、为数据创建其他可视化效果或与他人共享数据调查结果。

以前、数据调查报告导出限制为10、000行。此版本已删除限制、您可以导出所有数据。通过此更改、您可以从数据调查报告导出更多数据、从而提高数据分析的灵活性。

您可以选择工作环境、卷、目标文件夹以及JSON或CSV格式。导出的文件名包含一个时间戳、可帮助您确定数据的导出时间。

支持的工作环境包括：

* Cloud Volumes ONTAP
* 适用于 ONTAP 的 FSX
* ONTAP
* 共享组


从数据调查报告导出数据时存在以下限制：

* 要下载的最大记录数为5亿。每种类型(文件、目录和表)
* 100万条记录预计需要大约35分钟才能导出。


有关数据调查和报告的详细信息，请参见 https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["调查存储在组织中的数据"]。



== 2024年12月16日



=== 1.38 版

此BlueXP  分类版本包括一些常规改进和错误修复。



== 2024年11月4日



=== 1.37 版

此BlueXP  分类版本包含以下更新。

.支持RHEL 8.10
除了先前支持的版本之外、此版本还支持Red Hat Enterprise Linux v8.10。这适用于BlueXP  分类的任何手动内部安装、包括非公开站点部署。

以下操作系统要求使用Podman容器引擎、并要求使用BlueXP  分类版本1.3或更高版本：Red Hat Enterprise Linux版本8.8、8.10、9.0、9.1、9.2、9.3和9.4。

详细了解 https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["BlueXP分类"]。

.支持NFS v4.1
除了先前支持的版本之外、此版本还支持NFS v4.1。

详细了解 https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["BlueXP分类"]。



== 2024年10月10日



=== 1.36 版

.支持RHEL 9.4
除了先前支持的版本之外、此版本还支持Red Hat Enterprise Linux v9.4。这适用于BlueXP  分类的任何手动内部安装、包括非公开站点部署。

以下操作系统要求使用Podman容器引擎、并要求使用BlueXP  分类版本1.3或更高版本：Red Hat Enterprise Linux版本8.8、9.0、9.1、9.2、9.3和9.4。

详细了解 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-overview.html["BlueXP分类部署概述"]。

.提高了扫描性能
此版本可提高扫描性能。



== 2024年9月2日



=== 版本：1.

.扫描StorageGRID数据
BlueXP  分类现在可以在StorageGRID中扫描数据。

有关详细信息，请参见 link:task-scanning-storagegrid.html["扫描StorageGRID数据"]。



== 2024年8月5日



=== 1.34 版

此BlueXP  分类版本包含以下更新。

.从CentOS更改为Ubuntu
BlueXP  Classification已将适用于Microsoft Azure和Google Cloud Platform (GCP)的Linux操作系统从CentOS 7.9更新为Ubuntu 22.04。

有关部署的详细信息，请参见 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html#prepare-the-linux-host-system["在可访问Internet的Linux主机上安装并准备Linux主机系统"]。



== 2024年7月1日



=== 1.33 版

.支持Ubuntu
此版本支持Ubuntu 24.04 Linux平台。

.映射扫描可收集元数据
以下元数据在映射扫描期间从文件中提取、并显示在"监管"、"合规性"和"调查"信息板上：

* Working environment
* Working environment type
* 存储库
* 文件类型
* Used capacity
* 文件数
* 文件大小
* 文件创建
* 文件上次访问
* 文件上次修改时间
* 文件发现时间
* 权限提取


.信息板中的其他数据
此版本更新了映射扫描期间显示在"监管"、"合规性"和"调查"信息板中的数据。

有关详细信息，请参见 link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["映射扫描与分类扫描之间有何区别"]。



== 2024年6月5日



=== 1.32 版

.配置页面中的新建映射状态列
此版本现在会在配置页面中显示一个新的映射状态列。新列可帮助您确定映射正在运行、已排队、已暂停还是更多。

有关状态的说明，请参见 https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html["更改扫描设置"]。



== 2024年5月15日



=== 1.31 版

.分类可作为BlueXP中的核心服务提供
BlueXP分类现已作为BlueXP中的核心功能提供、无需额外付费即可处理高达500 TiB的扫描数据。不需要分类许可证或付费订阅。由于我们将BlueXP分类功能的重点放在扫描具有此新版本的NetApp存储系统上、因此、某些原有功能仅供以前已支付许可证费用的客户使用。这些原有功能的使用将在已支付合同到期后过期。

link:reference-free-paid.html["详细了解已弃用的功能"](英文)



== 2024年4月1日



=== 1.30 版

.增加了对RHEL v8.8和v9.3 BlueXP分类的支持
除了先前支持的9.x (需要Podman、而不是Docker引擎)之外、此版本还支持Red Hat Enterprise Linux v8.8和v9.3。这适用于BlueXP分类的任何手动内部安装。

以下操作系统要求使用Podman容器引擎、并要求BlueXP分类版本1.3或更高版本：Red Hat Enterprise Linux版本8.8、9.0、9.1、9.2和9.3。

详细了解 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-overview.html["BlueXP分类部署概述"]。

如果在内部的RHEL 8或9主机上安装Connector、则支持BlueXP分类。如果RHEL 8或9主机位于AWS、Azure或Google Cloud中、则不支持此功能。

.删除了用于激活审核日志收集的选项
已禁用用于激活审核日志收集的选项。

.扫描速度提高
二级扫描程序节点上的扫描性能已提高。如果您需要更多的扫描处理能力、可以添加更多的扫描程序节点。有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["在可访问Internet的主机上安装BlueXP分类"]。

.自动升级
如果您在可访问Internet的系统上部署了BlueXP分类、则系统将自动升级。以前、升级发生在自上次用户活动以来经过的特定时间之后。在此版本中、如果本地时间介于1：00 AM到5：00 AM之间、则BlueXP  分类会自动升级。如果本地时间不在这些时间内、则升级将在自上次用户活动后经过一段特定时间后进行。有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["在可访问Internet的Linux主机上安装"]。

如果您部署的BlueXP分类不能访问Internet、则需要手动升级。有关详细信息，请参见 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-dark-site.html["在无法访问Internet的Linux主机上安装BlueXP分类"]。



== 2024年3月4日



=== 1.29 版

.现在、您可以排除驻留在特定数据源目录中的扫描数据
如果希望BlueXP分类排除驻留在特定数据源目录中的扫描数据、则可以将这些目录名称添加到BlueXP分类处理的配置文件中。通过此功能、您可以避免扫描不必要的目录或可能导致返回误报的个人数据结果的目录。

https://docs.netapp.com/us-en/bluexp-classification/task-exclude-scan-paths.html["了解更多信息。"](英文)

.超大型实例支持现已通过认证
如果您需要BlueXP分类来扫描超过2.5亿个文件、则可以在云部署或内部安装中使用一个超大实例。此类系统最多可扫描5亿个文件。

https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html#using-a-smaller-instance-type["了解更多信息。"](英文)



== 2024年1月10日



=== 1.27 版

.现在、除了项目总数之外、调查页面结果还会显示总大小
现在、"调查"页面中经过筛选的结果除了显示文件总数之外、还会显示项目的总大小。这有助于移动文件、删除文件等。

.将其他组ID配置为"对组织开放"
现在、您可以在NFS中将组ID配置为直接从BlueXP分类中视为"对组织开放"(如果组最初未设置该权限)。附加了这些组ID的所有文件和文件夹将在"调查详细信息"页面中显示为"开放给组织"。请参见操作说明 https://docs.netapp.com/us-en/bluexp-classification/task-add-group-id-as-open.html["将其他组ID添加为"对组织开放""]。



== 2023年12月14日



=== 1.26.6版

此版本包含一些小的增强功能。

此版本还删除了以下选项：

* 已禁用用于激活审核日志收集的选项。
* 在目录调查期间、无法使用按目录计算个人身份信息(Personal可识别信息、个人身份信息、Personal可识别信息、请参阅 link:task-investigate-data.html["调查存储在组织中的数据"]。
* 已禁用使用Azure信息保护(AIP)标签集成数据的选项。请参阅 link:task-org-private-data.html["组织您的私有数据"]。




== 2023年11月6日



=== 1.26.3版

此版本已修复以下问题

* 修复了在信息板中显示系统扫描的文件数时出现的不一致问题。
* 通过处理和报告名称和元数据中包含特殊字符的文件和目录、改进了扫描行为。




== 2023年10月4日



=== 1.26 版

.支持在RHEL版本9上进行BlueXP分类的内部安装
Red Hat Enterprise Linux版本8和9不支持Docker引擎；BlueXP分类安装需要此引擎。现在、我们支持在使用Podman版本4或更高版本作为容器基础架构的RHEL 9.0、9.1和9.2上安装BlueXP分类。如果您的环境要求使用最新版本的RHEL、现在可以在使用Podman时安装BlueXP分类(1.26或更高版本)。

目前、在使用RHEL 9.x时、我们不支持非公开站点安装或分布式扫描环境(使用主扫描程序节点和远程扫描程序节点)



== 2023年9月5日



=== 1.25 版

.中小型部署暂时不可用
在AWS中部署BlueXP分类实例时、选择*部署>配置*并选择小型或中型实例的选项目前不可用。您仍然可以通过选择*Deploy > DEPLE*来使用较大实例大小来部署实例。

.在"调查结果"页面中对多达100、000个商品应用标记
过去、您一次只能在调查结果页面(20个项目)中对单个页面应用标记。现在、您可以在调查结果页面中选择*所有*项目、并将标记应用于所有项目-一次最多10万个项目。 https://docs.netapp.com/us-en/bluexp-classification/task-org-private-data.html#assign-tags-to-files["了解如何操作"](英文)。

.确定文件大小至少为1 MB的重复文件
BlueXP分类、用于仅在文件大于或等于50 MB时识别重复文件。现在、可以识别从1 MB开始的重复文件。您可以使用"调查"页面筛选"文件大小"和"重复项"、查看环境中具有特定大小的文件的重复项。



== 2023年7月17日



=== 1.24 版

.两种新类型的德国个人数据通过BlueXP分类来识别
BlueXP分类可以标识包含以下类型数据的文件并对其进行分类：

* 德语ID (Personalausweisnummer)
* 德国社会保障号码(Sozialversicherungsnummer)


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["查看BlueXP分类可在您的数据中识别的所有个人数据类型"](英文)

.在受限模式和专用模式下完全支持BlueXP分类
现在、在无法访问Internet (专用模式)且出站Internet访问受限(受限模式)的站点中、完全支持BlueXP  分类。 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["详细了解连接器的BlueXP部署模式"^](英文)。

.升级BlueXP分类的私有模式安装时可以跳过版本
现在、您可以升级到较新版本的BlueXP分类、即使它不是按顺序进行的。这意味着不再需要一次升级一个版本的BlueXP分类的当前限制。从1.24版开始、此功能是相关的。

.BlueXP分类API现已推出
通过BlueXP分类API、您可以执行操作、创建查询以及导出有关正在扫描的数据的信息。可使用Swagger获取交互式文档。文档分为多个类别、包括调查、合规性、监管和配置。每个类别都是BlueXP分类UI中各个选项卡的参考。

https://docs.netapp.com/us-en/bluexp-classification/api-classification.html["详细了解BlueXP分类API"](英文)



== 2023年6月6日



=== 1.23 版

.现在、搜索数据主题名称时支持日语
现在、在响应数据主体访问请求(Data Subject Access Request、DSAR)搜索主体名称时、可以输入日语名称。您可以使用生成的信息生成 https://docs.netapp.com/us-en/bluexp-classification/task-generating-compliance-reports.html["数据主体访问请求报告"]。您也可以在中输入日语名称 https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html[""数据调查"页面中的"数据主题"筛选器"]、以标识包含主题名称的文件。

.Ubuntu现在是一个受支持的Linux分发版、您可以在其中安装BlueXP分类
Ubuntu 22.04已被认定为BlueXP分类支持的操作系统。您可以在网络中的Ubuntu Linux主机上安装分类、也可以在云中的Linux主机上安装BlueXP  分类(如果使用安装程序版本1.23)。 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["了解如何在安装了Ubuntu的主机上安装BlueXP分类"](英文)。

.新的BlueXP分类安装不再支持Red Hat Enterprise Linux 8.6和8.7
新部署不支持这些版本、因为Red Hat不再支持Docker、而Docker是前提条件。如果现有BlueXP分类计算机运行RHEL 8.6或8.7、则NetApp将继续支持您的配置。

.可以将BlueXP分类配置为FPolicy收集器、以便从ONTAP系统接收FPolicy事件
您可以在BlueXP分类系统上为工作环境中的卷上检测到的文件访问事件收集文件访问审核日志。BlueXP分类可以捕获以下类型的FPolicy事件以及对文件执行操作的用户：创建、读取、写入、删除、重命名、 Change owner/permissions和Change SACL/DACL。

.现在、非公开站点支持Data sense BYOL许可证
现在、您可以将Data Sense BYOL许可证上传到非公开站点的BlueXP数字钱包中、以便在许可证不足时收到通知。



== 2023年4月3日



=== 1.22 版

.新的数据发现评估报告
数据发现评估报告对扫描环境进行了深入分析、以突出显示系统的发现结果、并显示关注领域和可能的修复步骤。本报告的目标是提高对数据集的数据监管问题、数据安全风险以及数据合规性差距的认识。 https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html["请参见如何生成和使用数据发现评估报告"](英文)。

.能够在云中的较小实例上部署BlueXP分类
在AWS环境中从BlueXP Connector部署BlueXP分类时、现在您可以从两种比默认实例更小的实例类型中进行选择。如果您要扫描小型环境、这可以帮助您节省云成本。但是、使用较小的实例时会有一些限制。 https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["请参见可用的实例类型和限制"](英文)。

.现在、可以使用独立脚本在安装BlueXP分类之前对Linux系统进行资格认定
如果要独立于运行BlueXP  分类安装来验证Linux系统是否满足所有前提条件、您可以下载一个单独的脚本、该脚本仅测试前提条件。 https://docs.netapp.com/us-en/bluexp-classification/task-test-linux-system.html["请参见How to check if your Linux host is ready to install BlueXP classification"](英文)。



== 2023年3月7日



=== 1.21 版

.新增了一项功能、可从BlueXP分类UI添加您自己的自定义类别
现在、您可以通过BlueXP分类添加自己的自定义类别、以便BlueXP分类能够识别适合这些类别的文件。BlueXP  分类有许多 https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["预定义的类别"]，因此，您可以通过此功能添加自定义类别，以确定在数据中您的组织所特有的信息的位置。

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["了解更多信息。"^](英文)

.现在、您可以从BlueXP分类UI添加自定义关键字
BlueXP分类可以添加BlueXP分类在未来扫描中识别的自定义关键字。但是、您需要登录到BlueXP classification Linux主机并使用命令行界面添加关键字。在此版本中、BlueXP分类UI中提供了添加自定义关键字的功能、因此可以轻松添加和编辑这些关键字。

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["了解有关从BlueXP分类UI添加自定义关键字的更多信息"^](英文)

.当"上次访问时间"将被更改时、BlueXP分类*不*扫描文件的功能
默认情况下、如果BlueXP分类没有足够的"写入"权限、则系统不会扫描卷中的文件、因为BlueXP分类无法将"上次访问时间"还原为原始时间戳。但是、如果您不在乎文件中的上次访问时间是否重置为原始时间、则可以在配置页面中覆盖此行为、以便BlueXP分类将扫描卷、而不管权限如何。

与此功能结合使用时、添加了名为"扫描分析事件"的新筛选器、因此您可以查看因BlueXP分类无法还原上次访问时间而未进行分类的文件、或者即使BlueXP分类无法还原上次访问时间也进行分类的文件。

https://docs.netapp.com/us-en/bluexp-classification/reference-collected-metadata.html["了解有关"上次访问时间时间戳"和BlueXP分类所需权限的更多信息"](英文)

.BlueXP分类标识了三种新类型的个人数据
BlueXP分类可以标识包含以下类型数据的文件并对其进行分类：

* 博茨瓦纳身份卡(Omang)编号
* 博茨瓦纳的护照编号
* 新加坡国家注册身份卡(NRIC)


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["查看BlueXP分类可在您的数据中识别的所有个人数据类型"](英文)

.更新了目录的功能
* 现在、数据调查报告的"轻型CSV报告"选项包括目录中的信息。
* "上次访问"时间筛选器现在可显示文件和目录的上次访问时间。


.安装增强功能
* 现在、不能访问Internet的站点(非公开站点)的BlueXP分类安装程序会执行预检查、以确保您的系统和网络要求已满足、以便成功安装。
* 安装审核日志文件将立即保存；它们将写入 `/ops/netapp/install_logs`。




== 2023年2月5日



=== 1.20 版

.能够将基于策略的通知电子邮件发送到任何电子邮件地址
在早期版本的BlueXP分类中、当某些关键策略返回结果时、您可以向帐户中的BlueXP用户发送电子邮件警报。通过此功能、您可以在未联机时收到通知以保护数据。现在、您还可以将策略中的电子邮件警报发送给不在您的BlueXP帐户中的任何其他用户、最多20个电子邮件地址。

https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html["了解有关根据策略结果发送电子邮件警报的更多信息"](英文)

.现在、您可以从BlueXP分类UI添加个人模式
BlueXP分类可以添加BlueXP分类在未来一段时间内将识别的自定义"个人数据"。但是、您需要登录到BlueXP classification Linux主机并使用命令行添加自定义模式。在此版本中、BlueXP分类UI中提供了使用正则表达式添加个人模式的功能、因此可以轻松添加和编辑这些自定义模式。

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["从BlueXP分类UI中了解有关添加自定义模式的更多信息"^](英文)

.能够使用BlueXP分类移动1、500万个文件
过去、您可以让BlueXP分类将最多100、000个源文件移动到任何NFS共享。现在、一次最多可以移动1500万个文件。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html["了解有关使用BlueXP分类移动源文件的更多信息"](英文)。

.能够查看有权访问SharePoint Online文件的用户数量
筛选器"可访问的用户数"现在支持存储在SharePoint Online存储库中的文件。过去仅支持CIFS共享上的文件。请注意、目前不会在此筛选器中计入非基于Active Directory的SharePoint组。

.已将新的"部分成功"状态添加到"操作状态"面板中
新的"部分成功"状态表示BlueXP分类操作已完成、某些项目失败、而某些项目成功、例如、当您移动或删除100个文件时。此外、"已完成"状态已重命名为"成功"。过去、"已完成"状态可能会列出成功和失败的操作。现在、"成功"状态意味着所有项目上的所有操作都成功。 https://docs.netapp.com/us-en/bluexp-classification/task-view-compliance-actions.html["请参见如何查看操作状态面板"](英文)。



== 2023年1月9日



=== 1.19 版

.可以查看包含敏感数据且过于宽松的文件图表
"监管"信息板添加了一个新的"敏感数据和宽权限"区域、用于为包含敏感数据(包括敏感和敏感个人数据)且过于宽松的文件提供热图。这有助于您了解敏感数据在哪些方面可能存在一些风险。 https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html["了解更多信息。"](英文)。

.数据调查页面提供了三个新筛选器
可以使用新筛选器细化数据调查页面中显示的结果：

* "Number of users with access"筛选器显示了哪些文件和文件夹对一定数量的用户开放。您可以选择一个数字范围来细化结果、例如、查看51-100个用户可访问哪些文件。
* 现在、"创建时间"、"发现时间"、"上次修改时间"和"上次访问时间"筛选器允许您创建自定义日期范围、而不是仅选择预定义的天数范围。例如、您可以查找"创建时间"为"超过6个月"或"最近10天"内"上次修改"日期的文件。
* 现在、您可以使用"文件路径"筛选器指定要从筛选的查询结果中排除的路径。如果您输入包含和排除某些数据的路径、BlueXP分类会首先查找包含路径中的所有文件、然后从排除的路径中删除文件、最后显示结果。


https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["查看可用于调查数据的所有筛选器的列表"](英文)

.BlueXP分类可以标识日语个人编号
BlueXP分类可以识别包含日语个人编号(也称为"我的编号")的文件并对其进行分类。这包括个人和公司我的号码。 https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["查看BlueXP分类可在您的数据中识别的所有个人数据类型"](英文)。
